using System.Text.RegularExpressions;

namespace MEPBMmanager.Domain.Constants;

// Wiki 2950 artifact table (ID, name, primary benefit, secondary power).
// Source: https://wiki.mepbm.com/artifacts/2950
public record ArtifactWikiEntry(int Id, string Name, string Primary, string Secondary, string Alignment);

public static class ArtifactCatalog2950
{
    public static readonly ArtifactWikiEntry[] All =
    [
        new(1, "Ring of Wind", "Agent +40", "-", "None"),
        new(2, "Ring of Stargazing", "Mage +25", "-", "None"),
        new(3, "Ring of Iron Magic", "Mage +30", "-", "Evil"),
        new(4, "Ring of Impersonation", "Agent +25", "-", "None"),
        new(5, "Ring of Barahir", "Command +35", "Bonus against Dragons & Fell Beasts", "Good"),
        new(6, "Ring of Axardil", "Command +10", "Cast Teleport Spell", "None"),
        new(7, "Nazguaga", "Mage +30", "Learn Dark Summons Spells", "Evil"),
        new(8, "Lorglin", "Mage +15", "-", "None"),
        new(9, "Elenya", "Stealth +15", "-", "None"),
        new(10, "Wolor Priest Ring", "Mage +20", "-", "None"),
        new(11, "Vilya", "Mage +50", "-", "None"),
        new(12, "Nenya", "Mage +50", "-", "None"),
        new(13, "Narya", "Mage +50", "-", "None"),
        new(14, "The One Ring", "Unknown", "-", "None"),
        new(15, "Tinculin", "Mage +40", "Learn Spirit Mastery Spells", "None"),
        new(16, "Mothras", "Combat +500", "Learn Random Lost List Spell", "None"),
        new(17, "Ring of Angrenost", "Combat +500", "-", "None"),
        new(18, "Tablets of Dark Knowledge", "Mage +15", "Learn Random Lost List Spell", "Evil"),
        new(19, "Staff of Storms", "Navy not lost at sea or affected by storms", "Learn Dark Summons Spells", "None"),
        new(20, "Staff of the Serpent", "Mage +10", "-", "None"),
        new(21, "Staff of Earthmastery", "Mage +20", "Learn Conjuring Ways Spells", "None"),
        new(22, "Rauzgnagli", "Combat +1750", "-", "Evil"),
        new(23, "Nedelhach", "Combat +750", "-", "None"),
        new(24, "Ghostbane", "Combat +750", "Bonus against Undead", "None"),
        new(25, "Staff of Bronze", "Mage +20", "-", "None"),
        new(26, "Mallorn Staff", "Mage +25", "-", "None"),
        new(27, "Palantir of Osgiliath", "Scrying", "-", "None"),
        new(28, "Palantir of Minas Ithil", "Scrying", "-", "None"),
        new(29, "Palantir of Minas Anor", "Scrying", "-", "None"),
        new(30, "Palantir of Orthanc", "Scrying", "-", "None"),
        new(31, "Palantir of Annuminas", "Scrying", "-", "None"),
        new(32, "Palantir of Elostirion", "Scrying", "-", "None"),
        new(33, "Palantir of Amon Sul", "Scrying", "-", "None"),
        new(34, "Orb of Dark Seeing", "Mage +20", "-", "Evil"),
        new(35, "Orb of Seeing", "Mage +35", "-", "None"),
        new(36, "Bone Ring", "Mage +15", "-", "None"),
        new(37, "Voice of the Dark Tower", "Emissary +20", "-", "Evil"),
        new(38, "Silver Rod of Aduni", "Command +25", "-", "Good"),
        new(39, "Miramarth", "Agent +15", "-", "Evil"),
        new(40, "Gaergil", "Navy not lost at sea or affected by storms", "-", "None"),
        new(41, "Mantle of Doriath", "Hides a Population Centre", "-", "Good"),
        new(42, "Collar of Might", "Mage +30", "-", "None"),
        new(43, "Cloak of the Heavens", "Agent +15", "-", "None"),
        new(44, "Collohwesta", "Stealth +25", "-", "None"),
        new(45, "Cloak of the Abyss", "Stealth +40", "-", "None"),
        new(46, "Robe of the Orc Priests", "Command +15", "-", "Evil"),
        new(47, "Belt of Durin", "Command +15", "-", "None"),
        new(48, "Thologaer Ciryatano", "Mage +30", "-", "None"),
        new(49, "Shield of Anarion", "Command +20", "-", "None"),
        new(50, "Ovir Crown", "Mage +15", "-", "None"),
        new(51, "Ossanna", "Mage +10", "-", "None"),
        new(52, "Morgul Plate", "Command +10", "-", "Evil"),
        new(53, "Listening Helm", "Agent +10", "-", "None"),
        new(54, "Helm of Sen Jey", "Command +15", "-", "None"),
        new(55, "Helm of Shadow", "Stealth +10", "-", "None"),
        new(56, "Helm of the Mumak-King", "Command +25", "Aids in recruiting & fighting Mumak", "None"),
        new(57, "Helm of Isildur", "Command +20", "-", "None"),
        new(58, "Helm of the Dark", "Command +15", "-", "Evil"),
        new(59, "Gaerennon", "Command +15", "-", "None"),
        new(60, "Durin's Armour and Shield", "Command +15", "-", "None"),
        new(61, "Dragon Helm of Dor-Lomin", "Command +15", "-", "Good"),
        new(62, "Dragon Helm and Armour", "Mage +30", "-", "Evil"),
        new(63, "Deepwood Bracelet", "Mage +10", "-", "None"),
        new(64, "Bracers of the Mist", "Stealth +30", "-", "None"),
        new(65, "Angbor", "Command +10", "-", "None"),
        new(66, "Bracers of Chennacatt", "Command +10", "-", "None"),
        new(67, "Ulukai", "Command +35", "-", "Evil"),
        new(68, "Thrakurghash", "Combat +500", "-", "Evil"),
        new(69, "Corantir", "Mage +10", "-", "None"),
        new(70, "Ring of Binding", "Agent +25", "-", "Evil"),
        new(71, "Talisman of Absorption", "Mage +20", "-", "Evil"),
        new(72, "Cloak of Duvorn", "Agent +20", "-", "None"),
        new(73, "Yellow Hammer", "Combat +500", "-", "None"),
        new(74, "War-dancer", "Combat +750", "-", "None"),
        new(75, "Vasamacil", "Combat +750", "-", "Evil"),
        new(76, "Usriev", "Combat +750", "-", "None"),
        new(77, "Ungolrist", "Combat +750", "Bonus when fighting Spiders", "Good"),
        new(78, "Sword of Soul Reducing", "Combat +500", "-", "Evil"),
        new(79, "Stormless Bow", "Combat +500", "-", "None"),
        new(80, "Snow Hammer", "Combat +500", "-", "None"),
        new(81, "Sil-Maegil", "Combat +750", "Bonus when fighting Evil Creatures", "Good"),
        new(82, "Romoquenaro", "Combat +750", "-", "None"),
        new(83, "Orcrist", "Combat +750", "-", "None"),
        new(84, "Ongrum", "Combat +500", "-", "Evil"),
        new(85, "Navron", "Combat +500", "-", "None"),
        new(86, "Nallagurth", "Combat +750", "Learn Spirit Mastery Spells", "Evil"),
        new(87, "Morlhach", "Combat +500", "-", "Evil"),
        new(88, "Macirille", "Combat +750", "-", "None"),
        new(89, "Macilromen", "Combat +1000", "-", "None"),
        new(90, "Helkaluine", "Combat +1250", "-", "Good"),
        new(91, "Gordur", "Combat +500", "-", "Good"),
        new(92, "Horse-Tamer", "Combat +500", "-", "None"),
        new(93, "Gurthdur", "Combat +500", "-", "Good"),
        new(94, "Glamdring", "Combat +1000", "-", "Good"),
        new(95, "Gildagor", "Combat +500", "-", "None"),
        new(96, "Fohnrad", "Combat +500", "-", "None"),
        new(97, "Fire's Edge", "Combat +750", "-", "Evil"),
        new(98, "Elhach", "Combat +1000", "-", "None"),
        new(99, "Elfhewer", "Combat +500", "-", "Evil"),
        new(100, "Elfbane", "Combat +500", "-", "Evil"),
        new(101, "E Voronwe", "Combat +500", "Cast Teleport Spell", "Good"),
        new(102, "Durin's Axe", "Combat +750", "Learn Conjuring Ways Spells", "None"),
        new(103, "Durcrist", "Combat +500", "Cast Perceive Nationality", "Good"),
        new(104, "Dawnsword", "Combat +750", "-", "Evil"),
        new(105, "Culok", "Combat +500", "-", "None"),
        new(106, "Cubragol", "Combat +500", "-", "None"),
        new(107, "Curaran", "Combat +500", "-", "None"),
        new(108, "Craig-olf-Ti", "Combat +500", "-", "None"),
        new(109, "Cloud Bow", "Combat +750", "-", "None"),
        new(110, "Cirmegil", "Combat +750", "-", "None"),
        new(111, "Believer's Bane", "Combat +500", "-", "None"),
        new(112, "Burning Blade", "Combat +500", "-", "Evil"),
        new(113, "Ar-Sil", "Combat +750", "-", "Good"),
        new(114, "Angian", "Combat +500", "-", "Good"),
        new(115, "Fire Mace", "Combat +750", "-", "None"),
        new(116, "Blood Spike", "Combat +750", "-", "None"),
        new(117, "Hatred Curse", "Combat +750", "-", "None"),
        new(118, "Skull Flail", "Combat +1000", "-", "None"),
        new(119, "Moon-Axe", "Combat +750", "-", "None"),
        new(120, "Amulet of Sea Mastery", "Navy not lost at sea or affected by storms", "-", "None"),
        new(121, "Troll Slayer", "Combat +750", "-", "Good"),
        new(122, "Orc Slayer", "Combat +750", "-", "Good"),
        new(123, "Wood-shadow", "Stealth +15", "-", "None"),
        new(124, "Robes of Aman", "Stealth +25", "-", "Good"),
        new(125, "Aeglin", "Combat +750", "-", "Good"),
        new(126, "Anarmacil", "Combat +750", "-", "Good"),
        new(127, "Aranruth", "Combat +1750", "Bonus when fighting evil creatures", "Good"),
        new(128, "Aratocam", "Combat +1000", "-", "None"),
        new(129, "Bow of Thunder and Bone", "Combat +500", "-", "None"),
        new(130, "Brodic Spear", "Combat +500", "-", "None"),
        new(131, "Caranlhach", "Combat +750", "-", "None"),
        new(132, "Daeron's Rapier", "Combat +1000", "-", "None"),
        new(133, "Dagger of Green Wisdom", "Combat +500", "Learn Conjuring Ways Spells", "None"),
        new(134, "Dagnirdraug", "Combat +750", "Bonus when fighting Wolves", "Good"),
        new(135, "Elenruth", "Combat +750", "Learn Spirit Mastery Spells", "None"),
        new(136, "Foamcleaver", "Combat +1500", "-", "None"),
        new(137, "Bloodrunner", "Combat +750", "Cast Major Heal", "None"),
        new(138, "Air-cleaver", "Combat +500", "-", "None"),
        new(139, "Gersebroc", "Combat +750", "Bonus against Dragons and Fell Beasts", "Good"),
        new(140, "Red Robes", "Command +10", "-", "None"),
        new(141, "Hue Changer", "Combat +500", "-", "None"),
        new(142, "Kirrauko", "Combat +1250", "-", "Good"),
        new(143, "Night Piercer", "Combat +500", "-", "None"),
        new(144, "Orcring", "Combat +2000", "-", "Good"),
        new(145, "Orcruin", "Combat +2000", "-", "Good"),
        new(146, "Horse-slayer", "Combat +500", "-", "None"),
        new(147, "Ringil", "Combat +2000", "-", "Good"),
        new(148, "Sickle of the Heavens", "Combat +1000", "-", "None"),
        new(149, "Sting", "Combat +500", "-", "Good"),
        new(150, "Stinging Tongue", "Combat +500", "-", "Evil"),
        new(151, "Troll-Cleaver", "Combat +2000", "-", "None"),
        new(152, "Turantir", "Combat +500", "Cast Teleport Spell", "Good"),
        new(153, "Water-skimmer", "Combat +750", "-", "None"),
        new(154, "Ring of Bleeding", "Mage +25", "-", "Evil"),
        new(155, "Taurin", "Combat +2000", "-", "None"),
        new(156, "Maranya", "Mage +30", "-", "None"),
        new(157, "Pectoral", "Emissary +30", "-", "None"),
        new(158, "Thunder's Edge", "Combat +1250", "-", "Evil"),
        new(159, "Skull Helm", "Command +15", "-", "Evil"),
        new(160, "Collar of Command", "Command +30", "-", "None"),
        new(161, "Erivagil", "Combat +1500", "-", "None"),
        new(162, "Glosovagil", "Combat +1500", "-", "None"),
        new(163, "Mirror of Galadriel", "Mage +40", "Scry Area", "Good"),
        new(164, "Tintelpe", "Combat +1750", "-", "Good"),
        new(165, "Cuiviegurth", "Combat +750", "-", "Evil"),
        new(166, "Calris", "Combat +750", "-", "Evil"),
        new(167, "Aedring", "Combat +1000", "-", "Good"),
        new(168, "Ancaruin", "Combat +2250", "Cast Teleport Spell", "Good"),
        new(169, "Gurthang", "Combat +2250", "Learn Spirit Mastery Spells", "Evil"),
        new(170, "Anguirel", "Combat +2250", "Learn Dark Summons Spells", "None"),
        new(171, "Aracu", "Combat +1500", "-", "Good"),
        new(172, "Axe of Braogha", "Combat +1000", "-", "None"),
        new(173, "Daecollo", "Stealth +20", "-", "None"),
        new(174, "Belthronding", "Combat +2250", "-", "Good"),
        new(175, "Ring of Curufin", "Agent +30", "-", "None"),
        new(176, "Spear of Bladorthin", "Combat +1250", "-", "None"),
        new(177, "Calninque", "Combat +1500", "-", "Good"),
        new(178, "Cubeleg", "Combat +750", "-", "None"),
        new(179, "Durcarak", "Combat +1250", "-", "Evil"),
        new(180, "Fuinrako", "Combat +2000", "Cast Teleport Spell", "Evil"),
        new(181, "Herugrim", "Combat +1000", "-", "Good"),
        new(182, "Morgurth", "Combat +1000", "-", "None"),
        new(183, "Silmaruth", "Combat +2000", "-", "None"),
        new(184, "Stone-mace of Setmaenen", "Combat +500", "Bonus against Undead", "Good"),
        new(185, "Headband of Slaeg", "Mage +10", "Learn Conjuring Ways Spells", "None"),
        new(186, "Sceptre of Hent", "Combat +750", "Bonus against Wolves", "Good"),
        new(187, "The Black Book", "Mage +10", "Cast Teleport Spell", "None"),
        new(188, "E Mere Vardo", "Mage +10", "Learn Spirit Mastery Spells", "Good"),
        new(189, "The Blue Ring", "Mage +10", "Learn Spirit Mastery Spells", "Evil"),
        new(190, "Staff of the Wanderer", "Mage +15", "Cast Teleport Spell", "Good"),
        new(191, "Aercrist", "Combat +750", "-", "None"),
        new(192, "Maikarama", "Combat +750", "Cast Long Stride Spell", "Good"),
        new(193, "Raukambar", "Combat +750", "-", "Good"),
        new(194, "Durlachiel", "Combat +750", "Cast Minor Heal Spell", "Good"),
        new(195, "Shards of Narsil", "Combat +750", "-", "Good"),
        new(196, "Mighty Blade", "Combat +750", "-", "None"),
        new(197, "Forest-blade", "Combat +750", "-", "Good"),
        new(198, "Flails of Horseslaying", "Combat +500", "-", "Evil"),
        new(199, "Guthwine", "Combat +750", "-", "Good"),
        new(200, "Mace of the Huntsman", "Combat +500", "-", "None"),
        new(201, "Runya", "Combat +500", "-", "Good"),
        new(202, "Sword of Cleaving", "Combat +750", "-", "None"),
        new(203, "Spear of Following", "Combat +500", "-", "None"),
        new(204, "Steward's Blade", "Combat +750", "Cast Capital Return Spell", "None"),
        new(205, "Sulhelka", "Combat +1000", "-", "None"),
        new(206, "Foam-light", "Command +15", "-", "None"),
        new(207, "Gulthalion", "Command +30", "-", "None"),
        new(208, "Horse-lord's Shield", "Command +20", "-", "None"),
        new(209, "Rat Gauntlets", "Agent +15", "-", "None"),
        new(210, "Boots of Iron", "Command +10", "-", "None"),
        new(211, "Cloak of Protection", "Agent +10", "-", "None"),
        new(212, "Cloak of Hiding", "Stealth +10", "-", "None"),
        new(213, "Cloak of Valacirca", "Stealth +10", "-", "None"),
    ];

    private static readonly Dictionary<string, ArtifactWikiEntry> ByName =
        All.ToDictionary(e => Norm(e.Name));

    public static ArtifactWikiEntry? Find(string? name)
    {
        if (string.IsNullOrWhiteSpace(name)) return null;
        return ByName.TryGetValue(Norm(name), out var e) ? e : null;
    }

    private static string Norm(string s) =>
        Regex.Replace(s.ToLowerInvariant().Replace('’', '\''), @"\s+", " ").Trim();
}
