using MEPBMmanager.Domain.Enums;

namespace MEPBMmanager.Domain.Constants;

public record OrderDefinition(int Code, string Abbreviation, string Name, string[] Restrictions, OrderDifficulty Difficulty, bool SkillIncrease, string Description);

// Restriction tokens (según reglamento MEPBM):
//   "cap" = Captain/Gobernante (ruler)   "c" = Commander   "com" = Commander/Ejército
//   "a" = Agent   "e" = Emissary   "m" = Mage   "without" = cualquier personaje (CH)
//   "fa" = orden de facción (Fourth Age)   [] = cualquiera
public static class OrderDefinitions
{
    public static readonly OrderDefinition[] Orders =
    [
        new(100, "Hold", "Hold Position", [], OrderDifficulty.Automatic, false, "Auto-generated hold order for inactive nations"),
        new(175, "ChAlleg", "Change Allegiance", ["c", "cap"], OrderDifficulty.Average, false, "Change nation allegiance between Free Peoples and Dark Servants"),
        new(180, "UpStNat", "Upgrade Relations", ["c", "cap"], OrderDifficulty.Easy, false, "Improve relations with another nation"),
        new(185, "DnStNat", "Downgrade Relations", ["c", "cap"], OrderDifficulty.Easy, false, "Worsen relations with another nation"),
        new(205, "UsCbArt", "Use Combat Artifact", [], OrderDifficulty.Automatic, false, "Equip a combat artifact"),
        new(210, "IssPers", "Issue Personal Challenge", [], OrderDifficulty.Automatic, true, "Challenge another character to single combat"),
        new(215, "RfsPers", "Refuse All Challenges", [], OrderDifficulty.Automatic, false, "Refuse all personal challenges this turn"),
        new(225, "CstCbSp", "Cast Combat Spell", ["m"], OrderDifficulty.Varies, true, "Cast a spell during combat"),
        new(230, "AttEnmy", "Attack Enemy", ["c", "com"], OrderDifficulty.Automatic, true, "Order army to attack an enemy army"),
        new(235, "AttNat", "Attack Nation", ["c", "com"], OrderDifficulty.Automatic, true, "Order army to attack a nation"),
        new(240, "Defend", "Defend", ["c", "com"], OrderDifficulty.Automatic, true, "Order army to defend position"),
        new(250, "DstPop", "Destroy Population Centre", ["c", "com"], OrderDifficulty.Automatic, true, "Destroy a captured population centre"),
        new(255, "CptrPop", "Capture Population Centre", ["c", "com"], OrderDifficulty.Automatic, true, "Capture a population centre"),
        new(260, "SiegPop", "Siege Population Centre", ["c", "com"], OrderDifficulty.Average, true, "Lay siege to a population centre"),
        new(270, "DstShp", "Destroy Ships", ["c", "com"], OrderDifficulty.Automatic, false, "Destroy ships"),
        new(275, "ScttShp", "Scuttle Ships", ["c", "com"], OrderDifficulty.Automatic, false, "Scuttle ships"),
        new(280, "AbanShp", "Abandon Ships", ["c", "cap"], OrderDifficulty.Automatic, false, "Abandon ships"),
        new(300, "ChTaxRt", "Change Tax Rate", ["c", "cap"], OrderDifficulty.Easy, false, "Change the national tax rate"),
        new(340, "TrPo2Ar", "Food: PC to Army", ["c"], OrderDifficulty.Automatic, false, "Transfer food from population centre to army"),
        new(345, "TrAr2Po", "Food: Army to PC", ["c"], OrderDifficulty.Automatic, false, "Transfer food from army to population centre"),
        new(347, "TrFood", "Food: Army to Army", ["c"], OrderDifficulty.Automatic, false, "Transfer food between armies"),
        new(349, "TrWarMa", "War Machines: Army-Army", ["c"], OrderDifficulty.Automatic, false, "Transfer war machines between armies"),
        new(351, "TrWpns", "Weapons: Army to Army", ["c"], OrderDifficulty.Automatic, false, "Transfer weapons between armies"),
        new(353, "TrArmr", "Armour: Army to Army", ["c"], OrderDifficulty.Automatic, false, "Transfer armour between armies"),
        new(355, "TrTrps", "Troops: Army to Army", ["c"], OrderDifficulty.Automatic, false, "Transfer troops between armies"),
        new(357, "TrShp", "Transfer Ships", ["c"], OrderDifficulty.Automatic, false, "Transfer ships between locations"),
        new(370, "UpWpns", "Upgrade Troop Weapons", ["c"], OrderDifficulty.Automatic, false, "Upgrade weapons for troops"),
        new(375, "UpArmr", "Upgrade Troop Armour", ["c"], OrderDifficulty.Automatic, false, "Upgrade armour for troops"),
        new(400, "HvCvlry", "Recruit Heavy Cavalry", ["c"], OrderDifficulty.Automatic, false, "Recruit heavy cavalry troops"),
        new(404, "LtCvlry", "Recruit Light Cavalry", ["c"], OrderDifficulty.Automatic, false, "Recruit light cavalry troops"),
        new(408, "HvInfan", "Recruit Heavy Infantry", ["c"], OrderDifficulty.Automatic, false, "Recruit heavy infantry troops"),
        new(412, "LtInfan", "Recruit Light Infantry", ["c"], OrderDifficulty.Automatic, false, "Recruit light infantry troops"),
        new(416, "Archers", "Recruit Archers", ["c"], OrderDifficulty.Automatic, false, "Recruit archer troops"),
        new(420, "MenAtAr", "Recruit Men-at-Arms", ["c"], OrderDifficulty.Automatic, false, "Recruit men-at-arms troops"),
        new(425, "RtrTrps", "Retire Troops", ["c"], OrderDifficulty.Automatic, false, "Retire troops from service"),
        new(430, "TrpsMan", "Troops on Manoeuvres", ["c"], OrderDifficulty.Automatic, true, "Put troops on manoeuvres for training"),
        new(435, "ArmyMan", "Army on Manoeuvres", ["c", "com"], OrderDifficulty.Automatic, true, "Put army on manoeuvres for training"),
        new(440, "MakWrMa", "Make War Machines", ["c"], OrderDifficulty.Automatic, false, "Construct war machines"),
        new(444, "MakArmr", "Make Armour", ["c"], OrderDifficulty.Automatic, false, "Construct armour"),
        new(448, "MakWpns", "Make Weapons", ["c"], OrderDifficulty.Automatic, false, "Construct weapons"),
        new(452, "MakWShp", "Make Warships", ["c"], OrderDifficulty.Automatic, false, "Construct warships"),
        new(456, "MakTShp", "Make Transports", ["c"], OrderDifficulty.Automatic, false, "Construct transport ships"),
        new(460, "RmvHar", "Remove Harbour", ["c"], OrderDifficulty.Easy, false, "Remove a harbour from a population centre"),
        new(465, "RmvPort", "Remove Port", ["c"], OrderDifficulty.Easy, false, "Remove a port from a population centre"),
        new(470, "DstStor", "Destroy PC Stores", ["c"], OrderDifficulty.Average, false, "Destroy stores at a population centre"),
        new(475, "DstBrdg", "Destroy Bridge", ["c"], OrderDifficulty.Average, false, "Destroy a bridge"),
        new(480, "RmvFort", "Remove Fortifications", ["c"], OrderDifficulty.Hard, false, "Remove fortifications from a population centre"),
        new(490, "BldBrdg", "Build Bridge", ["c"], OrderDifficulty.Average, false, "Build a bridge at a location"),
        new(494, "FortPop", "Fortify Population Centre", ["c"], OrderDifficulty.Average, true, "Add fortifications to a population centre"),
        new(498, "Threat", "Threaten Population Centre", ["c", "com"], OrderDifficulty.Hard, true, "Threaten a population centre to reduce loyalty"),
        new(725, "NamChar", "Name New Character", ["c", "cap"], OrderDifficulty.Automatic, false, "Create a new character"),
        new(728, "NamComm", "Name New Commander", ["c", "cap"], OrderDifficulty.Automatic, false, "Create a new commander character"),
        new(745, "CreCmpy", "Create Company", ["c", "com"], OrderDifficulty.Automatic, false, "Create a new company"),
        new(750, "DsbCmpy", "Disband Company", ["c", "company"], OrderDifficulty.Automatic, false, "Disband a company"),
        new(770, "HrArmy", "Hire Army", ["cap", "c"], OrderDifficulty.Automatic, false, "Hire a new army"),
        new(775, "DsbArmy", "Disband Army", ["c"], OrderDifficulty.Automatic, false, "Disband an army"),
        new(780, "TrComm", "Transfer Command", ["c", "com", "company"], OrderDifficulty.Automatic, false, "Transfer command to another character"),
        new(925, "Recon", "Recon Area", ["c"], OrderDifficulty.Easy, false, "Reconnoitre the surrounding area"),
        new(950, "ReloCap", "Relocate Capital", ["c", "cap"], OrderDifficulty.Easy, false, "Relocate the national capital"),

        // AGENT SKILL ORDERS
        new(600, "CntrEsp", "Counter Espionage", ["a"], OrderDifficulty.Average, true, "Counter enemy espionage operations"),
        new(605, "GrdLoc", "Guard Location", ["a"], OrderDifficulty.Automatic, true, "Guard a location against enemy agents"),
        new(610, "GrdChar", "Guard Character", ["a"], OrderDifficulty.Automatic, true, "Guard a character against assassination"),
        new(615, "Assass", "Assassinate Character", ["a"], OrderDifficulty.Hard, true, "Attempt to assassinate a character"),
        new(620, "Kidnap", "Kidnap Character", ["a"], OrderDifficulty.Hard, true, "Attempt to kidnap a character"),
        new(625, "Release", "Release Hostage", ["a"], OrderDifficulty.Automatic, false, "Release a hostage"),
        new(630, "Rescue", "Rescue Hostage", ["a"], OrderDifficulty.Hard, true, "Rescue a hostage from captivity"),
        new(635, "Interr", "Interrogate Hostage", ["a"], OrderDifficulty.Average, true, "Interrogate a hostage for information"),
        new(640, "Custody", "Take Custody of Hostage", ["a"], OrderDifficulty.Automatic, false, "Take custody of a hostage"),
        new(645, "Imprsn", "Imprison Hostage", ["a"], OrderDifficulty.Automatic, false, "Imprison a hostage"),
        new(650, "Execute", "Execute Hostage", ["a"], OrderDifficulty.Automatic, false, "Execute a hostage"),
        new(655, "RansDmd", "Demand Ransom", ["a"], OrderDifficulty.Automatic, false, "Demand ransom for a hostage"),
        new(665, "SabBrdg", "Sabotage Bridge", ["a"], OrderDifficulty.Hard, true, "Sabotage a bridge"),
        new(670, "SabFort", "Sabotage Fortifications", ["a"], OrderDifficulty.Hard, true, "Sabotage fortifications"),
        new(675, "SabPort", "Sabotage Harbour/Port", ["a"], OrderDifficulty.Hard, true, "Sabotage a harbour or port"),
        new(680, "SabStor", "Sabotage Production", ["a"], OrderDifficulty.Hard, true, "Sabotage production stores"),
        new(685, "StlArt", "Steal Artifact", ["a"], OrderDifficulty.Hard, true, "Attempt to steal an artifact"),
        new(690, "StlGold", "Steal Gold", ["a"], OrderDifficulty.Hard, true, "Attempt to steal gold"),
        new(731, "NamAgen", "Name New Agent", ["a", "cap"], OrderDifficulty.Automatic, false, "Create a new agent character"),
        new(905, "ScoArmy", "Scout Army", ["a"], OrderDifficulty.Average, false, "Scout an enemy army"),
        new(910, "ScoArea", "Scout Area", ["a"], OrderDifficulty.Automatic, false, "Scout the surrounding area"),
        new(915, "ScoHex", "Scout Hex", ["a"], OrderDifficulty.Easy, false, "Scout a specific hex"),
        new(920, "ScoPop", "Scout Population Centre", ["a"], OrderDifficulty.Easy, false, "Scout a population centre"),
        new(930, "ScoChar", "Scout for Characters", ["a"], OrderDifficulty.Average, false, "Scout for enemy characters"),

        // EMISSARY SKILL ORDERS
        new(500, "Double", "Recruit Double Agent", ["e"], OrderDifficulty.Average, true, "Recruit a double agent"),
        new(505, "Bribe", "Bribe/Influence Character", ["e"], OrderDifficulty.Average, true, "Bribe or influence a character"),
        new(520, "InfYour", "Influence Your PC Loyalty", ["e"], OrderDifficulty.Automatic, true, "Influence loyalty of your own population centre"),
        new(525, "InfOthr", "Influence Others PC Loyalty", ["e"], OrderDifficulty.Average, true, "Influence loyalty of another nation population centre"),
        new(530, "Har2Por", "Improve Harbour to Port", ["e"], OrderDifficulty.Easy, false, "Improve a harbour to a port"),
        new(535, "AddHar", "Add Harbour to PC", ["e"], OrderDifficulty.Easy, false, "Add a harbour to a population centre"),
        new(550, "ImprPop", "Improve Population Centre", ["e"], OrderDifficulty.Average, true, "Improve a population centre"),
        new(552, "PosCmp", "Post Camp", ["c", "com"], OrderDifficulty.Average, false, "Post a camp at current location"),
        new(555, "CreCmp", "Create Camp", ["e"], OrderDifficulty.Easy, true, "Create a new camp"),
        new(560, "AbanCmp", "Abandon Camp", ["e"], OrderDifficulty.Easy, false, "Abandon a camp"),
        new(565, "ReduPop", "Reduce Population Centre", ["e"], OrderDifficulty.Easy, false, "Reduce the size of a population centre"),
        new(580, "SprdRum", "Spread Rumours", ["e"], OrderDifficulty.Automatic, false, "Spread rumours to affect loyalty"),
        new(585, "Uncover", "Uncover Secrets", ["e"], OrderDifficulty.Average, false, "Uncover hidden information"),
        new(734, "NamEmis", "Name New Emissary", ["e", "cap"], OrderDifficulty.Automatic, false, "Create a new emissary character"),
        new(949, "TrOwner", "Transfer Ownership", ["e"], OrderDifficulty.Easy, false, "Transfer ownership of a population centre"),

        // MAGE SKILL ORDERS
        new(120, "CstHlSp", "Cast Heal Spell", ["m"], OrderDifficulty.Varies, true, "Cast a healing spell on a character"),
        new(330, "CstCjSp", "Cast Conjuring Spell", ["m"], OrderDifficulty.Varies, true, "Cast a conjuring spell"),
        new(700, "ForgtSp", "Forget Spell", ["m"], OrderDifficulty.Automatic, false, "Forget a known spell"),
        new(705, "RsrchSp", "Research Spell", ["m"], OrderDifficulty.Varies, true, "Research a new spell"),
        new(710, "PrenMgy", "Prentice Magery", ["m"], OrderDifficulty.Automatic, true, "Train an apprentice mage"),
        new(737, "NamMage", "Name New Mage", ["m", "cap"], OrderDifficulty.Automatic, false, "Create a new mage character"),
        new(940, "CstLoSp", "Cast Lore Spell", ["m"], OrderDifficulty.Varies, true, "Cast a lore spell for information"),

        // MOVEMENT ORDERS
        new(810, "MovChar", "Move Character", ["without"], OrderDifficulty.Automatic, false, "Move a character to a new location"),
        new(820, "MovCmpy", "Move Company", ["c", "company"], OrderDifficulty.Automatic, false, "Move a company to a new location"),
        new(825, "CstMvSp", "Cast Movement Spell", ["m", "without"], OrderDifficulty.Varies, true, "Cast a movement spell"),
        new(830, "MovNavy", "Move Navy", ["com"], OrderDifficulty.Automatic, false, "Move a navy unit"),
        new(840, "Stand", "Stand and Defend", ["com"], OrderDifficulty.Automatic, false, "Stand and defend position"),
        new(850, "MovArmy", "Move Army", ["com"], OrderDifficulty.Automatic, false, "Move an army to a new location"),
        new(860, "ForcMar", "Force March Army", ["com"], OrderDifficulty.Automatic, false, "Force march an army (faster but morale loss)"),
        new(870, "MovJoin", "Move Character & Join Army", ["without"], OrderDifficulty.Automatic, false, "Move character and join an army"),

        // MARKET ORDERS
        new(310, "BidCar", "Bid from Caravans", [], OrderDifficulty.Automatic, false, "Bid on goods from caravans"),
        new(315, "PrchCar", "Purchase from Caravans", [], OrderDifficulty.Automatic, false, "Purchase goods at market price"),
        new(320, "SellCar", "Sell to Caravans", [], OrderDifficulty.Automatic, false, "Sell goods at market price"),
        new(325, "NatSell", "Nation Sell to Caravans", ["cap"], OrderDifficulty.Automatic, false, "Nation-wide sell order"),

        // MISCELLANEOUS ORDERS
        new(285, "ReacEnc", "Reaction to Encounter", [], OrderDifficulty.Automatic, false, "React to an encounter"),
        new(290, "InvEnc", "Investigate Encounter", [], OrderDifficulty.Automatic, false, "Investigate an encounter"),
        new(360, "TrArt", "Transfer: Artifacts", [], OrderDifficulty.Automatic, false, "Transfer artifacts between characters"),
        new(363, "TrHost", "Transfer: Hostages", [], OrderDifficulty.Automatic, false, "Transfer hostages between characters"),
        new(660, "RansOff", "Offer Ransom", ["c", "cap"], OrderDifficulty.Automatic, false, "Offer ransom for a hostage"),
        new(740, "RtrChar", "Retire Character", [], OrderDifficulty.Automatic, false, "Retire a character"),
        new(755, "JnCmpy", "Join Company", [], OrderDifficulty.Automatic, false, "Join a company"),
        new(760, "LvCmpy", "Leave Company", ["without"], OrderDifficulty.Automatic, false, "Leave a company"),
        new(765, "SplArmy", "Split Army", ["c", "com"], OrderDifficulty.Automatic, false, "Split an army into two"),
        new(785, "JnArmy", "Join Army", ["without"], OrderDifficulty.Automatic, false, "Join an army"),
        new(790, "LvArmy", "Leave Army", ["without"], OrderDifficulty.Automatic, false, "Leave an army"),
        new(792, "DropArt", "Drop Artifact", [], OrderDifficulty.Automatic, false, "Drop an artifact"),
        new(794, "AnchShp", "Anchor Ships", ["c", "com"], OrderDifficulty.Automatic, false, "Anchor ships at a port"),
        new(796, "PickArt", "Pick up Artifact", [], OrderDifficulty.Easy, false, "Pick up an artifact"),
        new(798, "PickShp", "Pick up Ships", ["c", "com"], OrderDifficulty.Automatic, false, "Pick up ships"),
        new(805, "UsMvArt", "Use Movement Artifact", [], OrderDifficulty.Automatic, false, "Use a movement artifact"),
        new(900, "FindArt", "Find Artifact", [], OrderDifficulty.Hard, false, "Search for an artifact"),
        new(935, "UsScArt", "Use Scrying Artifact", [], OrderDifficulty.Automatic, false, "Use a scrying artifact"),
        new(942, "MvTnMap", "Move Turn Map", ["fa", "cap"], OrderDifficulty.Average, false, "Move the turn map (Fourth Age)"),
        new(945, "UsHiArt", "Use Hiding Artifact", [], OrderDifficulty.Automatic, false, "Use a hiding artifact"),
        new(947, "NatTran", "Nation Transport", ["cap"], OrderDifficulty.Automatic, false, "Transport goods nationally"),
        new(948, "TranCar", "Transport by Caravan", ["cap"], OrderDifficulty.Automatic, false, "Transport goods by caravan"),
        new(960, "IncrCar", "Increase Caravan Prices", ["fa", "cap"], OrderDifficulty.Hard, false, "Increase caravan prices"),
        new(965, "ReduCar", "Reduce Caravan Prices", ["fa", "cap"], OrderDifficulty.Hard, false, "Reduce caravan prices"),
        new(990, "OneRing", "The One Ring", [], OrderDifficulty.Automatic, false, "Attempt to use the One Ring"),
    ];
}
