using MEPBMmanager.Domain.Enums;

namespace MEPBMmanager.Domain.Constants;

public record SpellDefinition(int Id, string Name, SpellCategory Category, int MinCastingRank, string Description,
    string College = "", string Difficulty = "", string CastOrder = "", string Prerequisites = "",
    string RequiredInfo = "", string Effect = "");

public static class SpellDefinitions
{
    public static readonly SpellDefinition[] Spells =
    [
        // HEALING SPELLS
        new(2, "Minor Heal", SpellCategory.Healing, 10, "Heal minor wounds",
            College: "Healing Mastery", Difficulty: "Easy", CastOrder: "Cast Heal Spell - 120",
            Prerequisites: "Target character is at same location", RequiredInfo: "Target Character ID",
            Effect: "Increase target character's health by 20 points, or to maximum, whichever less."),
        new(4, "Major Heal", SpellCategory.Healing, 30, "Heal major wounds",
            College: "Healing Ways", Difficulty: "Easy", CastOrder: "Cast Heal Spell - 120",
            Prerequisites: "Target character is at same location", RequiredInfo: "Target Character ID",
            Effect: "Increase target character's health by 35 points, or to maximum, whichever less."),
        new(6, "Greater Heal", SpellCategory.Healing, 50, "Heal severe wounds",
            College: "Healing Ways", Difficulty: "Average", CastOrder: "Cast Heal Spell - 120",
            Prerequisites: "Target character is at same location", RequiredInfo: "Target Character ID",
            Effect: "Increase target character's health by 50 points, or to maximum, whichever less."),
        new(8, "Heal True", SpellCategory.Healing, 70, "Heal all wounds completely",
            College: "Healing Mastery", Difficulty: "Hard", CastOrder: "Cast Heal Spell - 120",
            Prerequisites: "Target character is at same location", RequiredInfo: "Target Character ID",
            Effect: "Increase target character's health to maximum."),

        // DEFENSIVE SPELLS
        new(102, "Barriers", SpellCategory.Defensive, 10, "Create magical barriers",
            College: "Barrier Mastery", Difficulty: "Easy", CastOrder: "Cast Combat Spell - 225",
            Prerequisites: "Character must be with an army unless practicing", RequiredInfo: "None",
            Effect: "Reduces damage inflicted on army character is with by 500 points, or navy by 5 points."),
        new(104, "Resistances", SpellCategory.Defensive, 20, "Grant magical resistances",
            College: "Resistance Mastery", Difficulty: "Easy", CastOrder: "Cast Combat Spell - 225",
            Prerequisites: "Character must be with an army unless practicing", RequiredInfo: "None",
            Effect: "Reduces damage inflicted on army character is with by 750 points, or navy by 7.5 points."),
        new(106, "Deflections", SpellCategory.Defensive, 30, "Deflect incoming attacks",
            College: "Barrier Mastery", Difficulty: "Average", CastOrder: "Cast Combat Spell - 225",
            Prerequisites: "Character must be with an army unless practicing", RequiredInfo: "None",
            Effect: "Reduces damage inflicted on army character is with by 1000 points, or navy by 10 points."),
        new(108, "Blessings", SpellCategory.Defensive, 40, "Bless troops for protection",
            College: "Resistance Mastery", Difficulty: "Average", CastOrder: "Cast Combat Spell - 225",
            Prerequisites: "Character must be with an army unless practicing", RequiredInfo: "None",
            Effect: "Reduces damage inflicted on army character is with by 1250 points, or navy by 12.5 points."),
        new(110, "Protections", SpellCategory.Defensive, 50, "Grant magical protections",
            College: "Resistance Mastery", Difficulty: "Hard", CastOrder: "Cast Combat Spell - 225",
            Prerequisites: "Character must be with an army unless practicing", RequiredInfo: "None",
            Effect: "Reduces damage inflicted on army character is with by 1500 points, or navy by 15 points."),
        new(112, "Shields", SpellCategory.Defensive, 60, "Create magical shields",
            College: "Barrier Mastery", Difficulty: "Hard", CastOrder: "Cast Combat Spell - 225",
            Prerequisites: "Character must be with an army unless practicing", RequiredInfo: "None",
            Effect: "Reduces damage inflicted on army character is with by 1750 points, or navy by 17.5 points."),
        new(114, "Barrier Walls", SpellCategory.Defensive, 70, "Create walls of barriers",
            College: "Barrier Mastery", Difficulty: "Hard", CastOrder: "Cast Combat Spell - 225",
            Prerequisites: "Character must be with an army unless practicing", RequiredInfo: "None",
            Effect: "Reduces damage inflicted on army character is with by 1500-2000 points, or navy by 15-20 points."),
        new(116, "Force Walls", SpellCategory.Defensive, 80, "Create walls of force",
            College: "Resistance Mastery", Difficulty: "Hard", CastOrder: "Cast Combat Spell - 225",
            Prerequisites: "Character must be with an army unless practicing", RequiredInfo: "None",
            Effect: "Reduces damage inflicted on army character is with by 1000-2000 points, or navy by 10-20 points."),

        // OFFENSIVE SPELLS
        new(202, "Call Fire", SpellCategory.Offensive, 10, "Call forth fire",
            College: "Fire Mastery", Difficulty: "Easy", CastOrder: "Cast Combat Spell - 225",
            Prerequisites: "Character must be with an army unless practicing", RequiredInfo: "None",
            Effect: "Increases damage inflicted by army character is with by 150 points, or navy by 1.5 points."),
        new(204, "Wild Flames", SpellCategory.Offensive, 15, "Unleash wild flames",
            College: "Fire Mastery", Difficulty: "Easy", CastOrder: "Cast Combat Spell - 225",
            Prerequisites: "Character must be with an army unless practicing", RequiredInfo: "None",
            Effect: "Increases damage inflicted by army character is with by 50-250 points, or navy by 0.5-2.5 points."),
        new(206, "Wall of Fire", SpellCategory.Offensive, 20, "Create a wall of fire",
            College: "Fire Mastery", Difficulty: "Easy", CastOrder: "Cast Combat Spell - 225",
            Prerequisites: "Character must be with an army unless practicing", RequiredInfo: "None",
            Effect: "Increases damage inflicted by army character is with by 100-200 points, or navy by 1-2 points."),
        new(208, "Words of Pain", SpellCategory.Offensive, 25, "Speak words of pain",
            College: "Word Mastery", Difficulty: "Easy", CastOrder: "Cast Combat Spell - 225",
            Prerequisites: "Character must be with an army unless practicing", RequiredInfo: "None",
            Effect: "Increases damage inflicted by army character is with by 250 points, or navy by 2.5 points."),
        new(210, "Words of Calm", SpellCategory.Offensive, 30, "Speak words of calm (defensive)",
            College: "Word Mastery", Difficulty: "Easy", CastOrder: "Cast Combat Spell - 225",
            Prerequisites: "Character must be with an army unless practicing", RequiredInfo: "None",
            Effect: "Increases damage inflicted by army character is with by 100-400 points, or navy by 1-4 points."),
        new(212, "Words of Paralysis", SpellCategory.Offensive, 35, "Paralyze enemies",
            College: "Word Mastery", Difficulty: "Easy", CastOrder: "Cast Combat Spell - 225",
            Prerequisites: "Character must be with an army unless practicing", RequiredInfo: "None",
            Effect: "Increases damage inflicted by army character is with by 200-300 points, or navy by 2-3 points."),
        new(214, "Call Winds", SpellCategory.Offensive, 40, "Call forth winds",
            College: "Wind Mastery", Difficulty: "Easy", CastOrder: "Cast Combat Spell - 225",
            Prerequisites: "Character must be with an army unless practicing", RequiredInfo: "None",
            Effect: "Increases damage inflicted by army character is with by 400 points, or navy by 4 points."),
        new(216, "Wild Winds", SpellCategory.Offensive, 45, "Unleash wild winds",
            College: "Wind Mastery", Difficulty: "Easy", CastOrder: "Cast Combat Spell - 225",
            Prerequisites: "Character must be with an army unless practicing", RequiredInfo: "None",
            Effect: "Increases damage inflicted by army character is with by 200-600 points, or navy by 2-6 points."),
        new(218, "Wall of Wind", SpellCategory.Offensive, 50, "Create a wall of wind",
            College: "Wind Mastery", Difficulty: "Easy", CastOrder: "Cast Combat Spell - 225",
            Prerequisites: "Character must be with an army unless practicing", RequiredInfo: "None",
            Effect: "Increases damage inflicted by army character is with by 300-500 points, or navy by 3-5 points."),
        new(220, "Words of Agony", SpellCategory.Offensive, 55, "Cause agony",
            College: "Word Mastery", Difficulty: "Average", CastOrder: "Cast Combat Spell - 225",
            Prerequisites: "Character must be with an army unless practicing", RequiredInfo: "None",
            Effect: "Increases damage inflicted by army character is with by 600 points, or navy by 6 points."),
        new(222, "Words of Stun", SpellCategory.Offensive, 60, "Stun enemies",
            College: "Word Mastery", Difficulty: "Average", CastOrder: "Cast Combat Spell - 225",
            Prerequisites: "Character must be with an army unless practicing", RequiredInfo: "None",
            Effect: "Increases damage inflicted by army character is with by 300-900 points, or navy by 3-9 points."),
        new(224, "Words of Command", SpellCategory.Offensive, 65, "Issue magical commands",
            College: "Word Mastery", Difficulty: "Average", CastOrder: "Cast Combat Spell - 225",
            Prerequisites: "Character must be with an army unless practicing", RequiredInfo: "None",
            Effect: "Increases damage inflicted by army character is with by 450-750 points, or navy by 4.5-7.5 points."),
        new(226, "Chill Bolts", SpellCategory.Offensive, 70, "Launch chill bolts",
            College: "Wind Mastery", Difficulty: "Average", CastOrder: "Cast Combat Spell - 225",
            Prerequisites: "Character must be with an army unless practicing", RequiredInfo: "None",
            Effect: "Increases damage inflicted by army character is with by 800 points, or navy by 8 points."),
        new(228, "Frost Balls", SpellCategory.Offensive, 75, "Launch frost balls",
            College: "Wind Mastery", Difficulty: "Average", CastOrder: "Cast Combat Spell - 225",
            Prerequisites: "Character must be with an army unless practicing", RequiredInfo: "None",
            Effect: "Increases damage inflicted by army character is with by 400-1200 points, or navy by 4-12 points."),
        new(230, "Wind Storms", SpellCategory.Offensive, 80, "Create wind storms",
            College: "Wind Mastery", Difficulty: "Average", CastOrder: "Cast Combat Spell - 225",
            Prerequisites: "Character must be with an army unless practicing", RequiredInfo: "None",
            Effect: "Increases damage inflicted by army character is with by 600-1000 points, or navy by 6-10 points."),
        new(232, "Fire Bolts", SpellCategory.Offensive, 85, "Launch fire bolts",
            College: "Fire Mastery", Difficulty: "Average", CastOrder: "Cast Combat Spell - 225",
            Prerequisites: "Character must be with an army unless practicing", RequiredInfo: "None",
            Effect: "Increases damage inflicted by army character is with by 1000 points, or navy by 10 points."),
        new(234, "Fire Balls", SpellCategory.Offensive, 90, "Launch fire balls",
            College: "Fire Mastery", Difficulty: "Average", CastOrder: "Cast Combat Spell - 225",
            Prerequisites: "Character must be with an army unless practicing", RequiredInfo: "None",
            Effect: "Increases damage inflicted by army character is with by 500-1500 points, or navy by 5-15 points."),
        new(236, "Fire Storms", SpellCategory.Offensive, 95, "Create fire storms",
            College: "Fire Mastery", Difficulty: "Average", CastOrder: "Cast Combat Spell - 225",
            Prerequisites: "Character must be with an army unless practicing", RequiredInfo: "None",
            Effect: "Increases damage inflicted by army character is with by 800-1200 points, or navy by 8-12 points."),
        new(238, "Summon Wind Spirits", SpellCategory.Offensive, 60, "Summon wind spirits",
            College: "Wind Mastery", Difficulty: "Hard", CastOrder: "Cast Combat Spell - 225",
            Prerequisites: "Character must be with an army unless practicing", RequiredInfo: "None",
            Effect: "Increases damage inflicted by army character is with by 750-1750 points, or navy by 7.5-17.5 points."),
        new(240, "Summon Fire Spirits", SpellCategory.Offensive, 70, "Summon fire spirits",
            College: "Fire Mastery", Difficulty: "Hard", CastOrder: "Cast Combat Spell - 225",
            Prerequisites: "Character must be with an army unless practicing", RequiredInfo: "None",
            Effect: "Increases damage inflicted by army character is with by 1000-2000 points, or navy by 10-20 points."),
        new(242, "Words of Death", SpellCategory.Offensive, 80, "Speak words of death",
            College: "Word Mastery", Difficulty: "Hard", CastOrder: "Cast Combat Spell - 225",
            Prerequisites: "Character must be with an army unless practicing", RequiredInfo: "None",
            Effect: "Increases damage inflicted by army character is with by 1250-2250 points, or navy by 12.5-22.5 points."),
        new(244, "Fearful Hearts", SpellCategory.Offensive, 85, "Cause fear in hearts",
            College: "Dark Summons", Difficulty: "Average", CastOrder: "Cast Combat Spell - 225",
            Prerequisites: "Character must be with an army unless practicing. Only Dark Servants may learn.",
            RequiredInfo: "None",
            Effect: "Reduces morale of enemy armies and navies in hex by 10-20 points. Multiple castings same turn not cumulative, best result used."),
        new(246, "Summon Storms", SpellCategory.Offensive, 90, "Summon storms",
            College: "Dark Summons", Difficulty: "Average", CastOrder: "Cast Combat Spell - 225",
            Prerequisites: "Character must be with an army unless practicing. Only Dark Servants may learn.",
            RequiredInfo: "None",
            Effect: "Forces enemy armies and navies in hex to use standard battle tactics during combat."),
        new(248, "Fanaticism", SpellCategory.Offensive, 95, "Inspire fanaticism",
            College: "Dark Summons", Difficulty: "Average", CastOrder: "Cast Combat Spell - 225",
            Prerequisites: "Character must be with an army unless practicing. Only Dark Servants may learn.",
            RequiredInfo: "None",
            Effect: "Increases morale of all national armies and navies in hex by 5-15 points for combat duration. Multiple castings same turn not cumulative, best used."),

        // MOVEMENT SPELLS
        new(302, "Long Stride", SpellCategory.Movement, 10, "Increase movement range",
            College: "Movement Mastery", Difficulty: "Easy", CastOrder: "Cast Movement Spell - 825",
            Prerequisites: "Destination within 14 hexes. Not an army, navy or company commander.",
            RequiredInfo: "Destination hex",
            Effect: "Move to any land hex within 14 hexes. Cannot move from a water hex. Hostages travel with character."),
        new(304, "Fast Stride", SpellCategory.Movement, 20, "Greatly increase movement",
            College: "Movement Mastery", Difficulty: "Average", CastOrder: "Cast Movement Spell - 825",
            Prerequisites: "Destination within 16 hexes. Not an army, navy or company commander.",
            RequiredInfo: "Destination hex",
            Effect: "Move to any land hex within 16 hexes. Cannot move from a water hex. Hostages travel with character."),
        new(306, "Path Mastery", SpellCategory.Movement, 30, "Master all paths",
            College: "Movement Mastery", Difficulty: "Hard", CastOrder: "Cast Movement Spell - 825",
            Prerequisites: "Destination within 19 hexes. Not an army, navy or company commander.",
            RequiredInfo: "Destination hex",
            Effect: "Move to any land hex within 19 hexes. Cannot move from a water hex. Hostages travel with character."),
        new(308, "Capital Return", SpellCategory.Movement, 40, "Return to capital",
            College: "Return Mastery", Difficulty: "Easy", CastOrder: "Cast Movement Spell - 825",
            Prerequisites: "Destination is the capital of the character's nation. Not an army, navy or company commander.",
            RequiredInfo: "Destination hex",
            Effect: "Move to the hex containing the capital. Cannot move from a water hex. Hostages travel with character."),
        new(310, "Major Return", SpellCategory.Movement, 50, "Return to major town",
            College: "Return Mastery", Difficulty: "Average", CastOrder: "Cast Movement Spell - 825",
            Prerequisites: "Destination has a major town or city of the character's nation. Not an army, navy or company commander.",
            RequiredInfo: "Destination hex",
            Effect: "Move to a hex with a city or major town of the nation. Cannot move from a water hex. Hostages travel with character."),
        new(312, "Return True", SpellCategory.Movement, 60, "Return to any friendly PC",
            College: "Return Mastery", Difficulty: "Hard", CastOrder: "Cast Movement Spell - 825",
            Prerequisites: "Destination has a population centre of the character's nation. Not an army, navy or company commander.",
            RequiredInfo: "Destination hex",
            Effect: "Move to a hex with a population centre of the nation. Cannot move from a water hex. Hostages travel with character."),
        new(314, "Teleport", SpellCategory.Movement, 80, "Teleport to any location",
            College: "Teleport Mastery", Difficulty: "Average", CastOrder: "Cast Movement Spell - 825",
            Prerequisites: "Not an army, navy or company commander.", RequiredInfo: "Destination hex",
            Effect: "Move to any land hex. Cannot move from a water hex. Hostages travel with character."),

        // LORE SPELLS
        new(402, "Perceive Allegiance", SpellCategory.Lore, 10, "Perceive nation allegiance",
            College: "Perceptions", Difficulty: "Easy", CastOrder: "Cast Lore Spell - 940",
            Prerequisites: "None", RequiredInfo: "Allegiance (Free Peoples, Neutral, or Dark Servants)",
            Effect: "Discover all nations currently of the specified allegiance."),
        new(404, "Perceive Relations", SpellCategory.Lore, 15, "Perceive nation relations",
            College: "Perceptions", Difficulty: "Easy", CastOrder: "Cast Lore Spell - 940",
            Prerequisites: "None", RequiredInfo: "Target nation",
            Effect: "Discover the relations that the specified nation has towards the character's nation."),
        new(406, "Divine Army", SpellCategory.Lore, 20, "Divine information about armies",
            College: "Divinations", Difficulty: "Easy", CastOrder: "Cast Lore Spell - 940",
            Prerequisites: "None", RequiredInfo: "Character ID of army or navy commander",
            Effect: "Discover the location of the target commander's army or navy, to within one hex. The commander must command or have commanded it during the turn."),
        new(408, "Perceive Nationality", SpellCategory.Lore, 25, "Perceive character nationality",
            College: "Perceptions", Difficulty: "Easy", CastOrder: "Cast Lore Spell - 940",
            Prerequisites: "None", RequiredInfo: "Target character ID",
            Effect: "Discover the nationality of the target character."),
        new(410, "Divine Allegiance Forces", SpellCategory.Lore, 30, "Divine allegiance forces",
            College: "Divinations", Difficulty: "Easy", CastOrder: "Cast Lore Spell - 940",
            Prerequisites: "None", RequiredInfo: "Allegiance",
            Effect: "Discover the presence of any forces of the specified allegiance within 6 hexes. Hex locations are not revealed."),
        new(412, "Research Artifact", SpellCategory.Lore, 35, "Research an artifact",
            College: "Artifact Lore", Difficulty: "Easy", CastOrder: "Cast Lore Spell - 940",
            Prerequisites: "None", RequiredInfo: "Artifact ID",
            Effect: "Discover some or all powers, type and alignment of the artifact, per proficiency and artifact level. No possession needed."),
        new(413, "Scry Population Centre", SpellCategory.Lore, 40, "Scry a population centre",
            College: "Scrying", Difficulty: "Easy", CastOrder: "Cast Lore Spell - 940",
            Prerequisites: "Target hex within 12 hexes of the character", RequiredInfo: "Target hex",
            Effect: "Discover name, owner, loyalty, size, fortifications, port/harbour, production, stores, siege and hidden status, capital, and foreign forces."),
        new(414, "Scry Hex", SpellCategory.Lore, 45, "Scry a hex",
            College: "Scrying", Difficulty: "Easy", CastOrder: "Cast Lore Spell - 940",
            Prerequisites: "Target hex within 12 hexes of the character", RequiredInfo: "Target hex",
            Effect: "Discover terrain, climate, production, anchored ships, pop centre presence and foreign armies/navies."),
        new(415, "Scry Area", SpellCategory.Lore, 50, "Scry an area",
            College: "Scrying", Difficulty: "Average", CastOrder: "Cast Lore Spell - 940",
            Prerequisites: "Target hex within 12 hexes of the character", RequiredInfo: "Target hex",
            Effect: "Gain a map of the hex and the six surrounding hexes with armies, pop centres, commanders and troop numbers."),
        new(416, "Reveal Production", SpellCategory.Lore, 55, "Reveal PC production",
            College: "Hidden Visions", Difficulty: "Easy", CastOrder: "Cast Lore Spell - 940",
            Prerequisites: "None", RequiredInfo: "Production type",
            Effect: "Locate up to five hexes within three hexes containing the specified production type, in random order."),
        new(417, "Divine Characters With Forces", SpellCategory.Lore, 60, "Divine characters with forces",
            College: "Divinations", Difficulty: "Average", CastOrder: "Cast Lore Spell - 940",
            Prerequisites: "Army or navy within 12 hexes of the character", RequiredInfo: "Character ID of army or navy commander",
            Effect: "Identify the characters travelling with the targeted army or navy. Location is not revealed."),
        new(418, "Locate Artifact", SpellCategory.Lore, 65, "Locate an artifact",
            College: "Artifact Lore", Difficulty: "Average", CastOrder: "Cast Lore Spell - 940",
            Prerequisites: "None", RequiredInfo: "Artifact ID",
            Effect: "Discover the location of the artifact to within 1 hex, and whether it is held, per proficiency and artifact level."),
        new(419, "Divine Nation Forces", SpellCategory.Lore, 70, "Divine nation forces",
            College: "Divinations", Difficulty: "Average", CastOrder: "Cast Lore Spell - 940",
            Prerequisites: "None", RequiredInfo: "Target nation",
            Effect: "Locate all armies and navies of the target nation within six hexes. Only commander's name and location revealed."),
        new(420, "Reveal Character", SpellCategory.Lore, 75, "Reveal a hidden character",
            College: "Hidden Visions", Difficulty: "Average", CastOrder: "Cast Lore Spell - 940",
            Prerequisites: "None", RequiredInfo: "Target character ID",
            Effect: "Locate the specified character to within 1 hex of its actual location."),
        new(422, "Perceive Power", SpellCategory.Lore, 80, "Perceive magical power",
            College: "Perceptions", Difficulty: "Average", CastOrder: "Cast Lore Spell - 940",
            Prerequisites: "None", RequiredInfo: "Target character ID",
            Effect: "Discover the skill rank titles of the target character."),
        new(424, "Perceive Mission", SpellCategory.Lore, 85, "Perceive character mission",
            College: "Perceptions", Difficulty: "Average", CastOrder: "Cast Lore Spell - 940",
            Prerequisites: "Target character is active", RequiredInfo: "Target character ID",
            Effect: "Discover the current orders of the target character."),
        new(426, "Divine Army True", SpellCategory.Lore, 90, "Divine army information perfectly",
            College: "Divinations", Difficulty: "Hard", CastOrder: "Cast Lore Spell - 940",
            Prerequisites: "None", RequiredInfo: "Character ID of army or navy commander",
            Effect: "Determine the exact location of the target commander's army or navy. The commander must command or have commanded it during the turn."),
        new(428, "Locate Artifact True", SpellCategory.Lore, 95, "Locate artifact perfectly",
            College: "Artifact Lore", Difficulty: "Hard", CastOrder: "Cast Lore Spell - 940",
            Prerequisites: "None", RequiredInfo: "Artifact ID",
            Effect: "Discover the exact location of the artifact, and whether it is held, per proficiency, mage rank and artifact level."),
        new(430, "Reveal Character True", SpellCategory.Lore, 100, "Reveal character perfectly",
            College: "Hidden Visions", Difficulty: "Hard", CastOrder: "Cast Lore Spell - 940",
            Prerequisites: "None", RequiredInfo: "Target character ID",
            Effect: "Locate the specified character's exact location."),
        new(432, "Perceive Secrets", SpellCategory.Lore, 60, "Perceive hidden secrets",
            College: "Perceptions", Difficulty: "Hard", CastOrder: "Cast Lore Spell - 940",
            Prerequisites: "None", RequiredInfo: "Target nation",
            Effect: "Discover the target nation's victory conditions, capital location and status (active, inactive or eliminated)."),
        new(434, "Reveal Population Centre", SpellCategory.Lore, 70, "Reveal hidden PC",
            College: "Hidden Visions", Difficulty: "Hard", CastOrder: "Cast Lore Spell - 940",
            Prerequisites: "None", RequiredInfo: "Target hex",
            Effect: "Reveal whether a hidden pop centre lies in the target hex. No automatic unhide."),
        new(436, "Scry Character", SpellCategory.Lore, 50, "Scry a character",
            College: "Scrying", Difficulty: "Hard", CastOrder: "Cast Lore Spell - 940",
            Prerequisites: "None", RequiredInfo: "Target character ID",
            Effect: "Discover skill rank titles, artifacts held and spells known by the target. Hex location not revealed."),

        // CONJURING SPELLS
        new(502, "Weakness", SpellCategory.Conjuring, 40, "Conjure weakness (lost spell)",
            College: "Spirit Mastery", Difficulty: "Easy", CastOrder: "Cast Conjuring Spell - 330",
            Prerequisites: "Target in same hex and of a different nation", RequiredInfo: "Target character ID",
            Effect: "Target loses health equal to natural mage rank divided by three, rounded down."),
        new(504, "Sickness", SpellCategory.Conjuring, 50, "Conjure sickness (lost spell)",
            College: "Spirit Mastery", Difficulty: "Average", CastOrder: "Cast Conjuring Spell - 330",
            Prerequisites: "Target in same hex and of a different nation", RequiredInfo: "Target character ID",
            Effect: "Target loses health equal to natural mage rank divided by two, rounded down."),
        new(506, "Curses", SpellCategory.Conjuring, 60, "Conjure curses (lost spell)",
            College: "Spirit Mastery", Difficulty: "Hard", CastOrder: "Cast Conjuring Spell - 330",
            Prerequisites: "Target in same or adjacent hex and of a different nation", RequiredInfo: "Target character ID",
            Effect: "Target loses health equal to natural mage rank divided by two, rounded down."),
        new(508, "Conjure Mounts", SpellCategory.Conjuring, 70, "Conjure mounts (lost spell)",
            College: "Conjuring Ways", Difficulty: "Easy", CastOrder: "Cast Conjuring Spell - 330",
            Prerequisites: "At a population centre of their own nation", RequiredInfo: "Optional number of mounts (0 = maximum)",
            Effect: "Conjure up to 5 mounts per point of natural mage rank."),
        new(510, "Conjure Food", SpellCategory.Conjuring, 80, "Conjure food (lost spell)",
            College: "Conjuring Ways", Difficulty: "Average", CastOrder: "Cast Conjuring Spell - 330",
            Prerequisites: "At own nation pop centre, or with an army or navy", RequiredInfo: "Optional number of food (0 = maximum)",
            Effect: "Conjure up to 25 food per natural mage rank. Goes to army/navy if with one, else to pop stores."),
        new(512, "Conjure Hordes", SpellCategory.Conjuring, 90, "Conjure hordes (lost spell, DS only)",
            College: "Conjuring Ways", Difficulty: "Average", CastOrder: "Cast Conjuring Spell - 330",
            Prerequisites: "With an army or navy. Dark Servants only.", RequiredInfo: "Optional number of troops (0 = maximum)",
            Effect: "Conjure up to 5 men-at-arms per natural mage rank: wooden weapons, no armour, poor training."),
    ];
}
