// <auto-generated />
using System;
using MEPBMmanager.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MEPBMmanager.Infrastructure.Migrations
{
    [DbContext(typeof(MepbmDbContext))]
    [Migration("20260914100800_AddSpellRank")]
    partial class AddSpellRank
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MEPBMmanager.Domain.Entities.Army", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("ArcherArmourRank")
                        .HasColumnType("integer");

                    b.Property<int>("ArcherWeaponRank")
                        .HasColumnType("integer");

                    b.Property<int>("Archers")
                        .HasColumnType("integer");

                    b.Property<string>("CommanderId")
                        .HasColumnType("text");

                    b.Property<int>("Food")
                        .HasColumnType("integer");

                    b.Property<int>("HCArmourRank")
                        .HasColumnType("integer");

                    b.Property<int>("HCWeaponRank")
                        .HasColumnType("integer");

                    b.Property<int>("HIArmourRank")
                        .HasColumnType("integer");

                    b.Property<int>("HIWeaponRank")
                        .HasColumnType("integer");

                    b.Property<int>("HeavyCavalry")
                        .HasColumnType("integer");

                    b.Property<int>("HeavyInfantry")
                        .HasColumnType("integer");

                    b.Property<bool>("IsOnManoeuvres")
                        .HasColumnType("boolean");

                    b.Property<int>("LCArmourRank")
                        .HasColumnType("integer");

                    b.Property<int>("LCWeaponRank")
                        .HasColumnType("integer");

                    b.Property<int>("LIArmourRank")
                        .HasColumnType("integer");

                    b.Property<int>("LIWeaponRank")
                        .HasColumnType("integer");

                    b.Property<int>("LightCavalry")
                        .HasColumnType("integer");

                    b.Property<int>("LightInfantry")
                        .HasColumnType("integer");

                    b.Property<string>("LocationHex")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("MAAArmourRank")
                        .HasColumnType("integer");

                    b.Property<int>("MAAWeaponRank")
                        .HasColumnType("integer");

                    b.Property<int>("MenAtArms")
                        .HasColumnType("integer");

                    b.Property<int>("Morale")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NationId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Training")
                        .HasColumnType("integer");

                    b.Property<int>("WarMachines")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("NationId");

                    b.ToTable("Armies");
                });

            modelBuilder.Entity("MEPBMmanager.Domain.Entities.Artifact", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Alignment")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Bonus")
                        .HasColumnType("integer");

                    b.Property<string>("HeldByCharacterId")
                        .HasColumnType("text");

                    b.Property<bool>("IsAtCapital")
                        .HasColumnType("boolean");

                    b.Property<string>("LocationHex")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NationId")
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("HeldByCharacterId");

                    b.ToTable("Artifacts");
                });

            modelBuilder.Entity("MEPBMmanager.Domain.Entities.Character", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AgentSkill")
                        .HasColumnType("integer");

                    b.Property<string>("ArmyId")
                        .HasColumnType("text");

                    b.Property<int>("ChallengeRank")
                        .HasColumnType("integer");

                    b.Property<int>("CommandSkill")
                        .HasColumnType("integer");

                    b.Property<string>("CompanyId")
                        .HasColumnType("text");

                    b.Property<int>("EmissarySkill")
                        .HasColumnType("integer");

                    b.Property<int>("Health")
                        .HasColumnType("integer");

                    b.Property<string>("HeldByNationId")
                        .HasColumnType("text");

                    b.Property<bool>("IsChampion")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDead")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsKidnapped")
                        .HasColumnType("boolean");

                    b.Property<string>("LocationHex")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("MageSkill")
                        .HasColumnType("integer");

                    b.Property<int>("MaxHealth")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NationId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Stealth")
                        .HasColumnType("integer");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ArmyId");

                    b.HasIndex("CompanyId");

                    b.HasIndex("NationId");

                    b.ToTable("Characters");
                });

            modelBuilder.Entity("MEPBMmanager.Domain.Entities.Company", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("LocationHex")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NationId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("NationId");

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("MEPBMmanager.Domain.Entities.Encounter", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ArmyId")
                        .HasColumnType("text");

                    b.Property<string>("CharacterId")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GameId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsResolved")
                        .HasColumnType("boolean");

                    b.Property<string>("LocationHex")
                        .HasColumnType("text");

                    b.Property<string>("Result")
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ArmyId");

                    b.HasIndex("CharacterId");

                    b.HasIndex("GameId");

                    b.ToTable("Encounters");
                });

            modelBuilder.Entity("MEPBMmanager.Domain.Entities.Game", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CurrentTurn")
                        .HasColumnType("integer");

                    b.Property<string>("GameTypeId")
                        .HasColumnType("text");

                    b.Property<int>("MaxTurns")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TurnIntervalDays")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("GameTypeId");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("MEPBMmanager.Domain.Entities.GameAdmin", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateTime?>("AcceptedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GameId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsReady")
                        .HasColumnType("boolean");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("GameId", "UserId")
                        .IsUnique();

                    b.ToTable("GameAdmins");
                });

            modelBuilder.Entity("MEPBMmanager.Domain.Entities.GameEvent", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GameId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TurnId")
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.HasIndex("TurnId");

                    b.ToTable("GameEvents");
                });

            modelBuilder.Entity("MEPBMmanager.Domain.Entities.GameType", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("GameTypes");
                });

            modelBuilder.Entity("MEPBMmanager.Domain.Entities.Guard", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("CharacterId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TargetId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.ToTable("Guards");
                });

            modelBuilder.Entity("MEPBMmanager.Domain.Entities.HexTile", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("GameId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GameTypeId")
                        .HasColumnType("text");

                    b.Property<bool>("HasBridge")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("HasFord")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("HasMajorRiver")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("HasMinorRiver")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("HasRoad")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("OwnerId")
                        .HasColumnType("text");

                    b.Property<int>("Q")
                        .HasColumnType("integer");

                    b.Property<int>("R")
                        .HasColumnType("integer");

                    b.Property<string>("Terrain")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("GameTypeId");

                    b.HasIndex("GameId", "Q", "R")
                        .IsUnique();

                    b.ToTable("HexTiles");
                });

            modelBuilder.Entity("MEPBMmanager.Domain.Entities.MarketPrice", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("BuyPrice")
                        .HasColumnType("integer");

                    b.Property<string>("GameId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Good")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SellPrice")
                        .HasColumnType("integer");

                    b.Property<int>("Supply")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("GameId", "Good")
                        .IsUnique();

                    b.ToTable("MarketPrices");
                });

            modelBuilder.Entity("MEPBMmanager.Domain.Entities.Message", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GameId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<string>("SenderId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.HasIndex("SenderId");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("MEPBMmanager.Domain.Entities.Nation", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Allegiance")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Bronze")
                        .HasColumnType("integer");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("EliminatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Food")
                        .HasColumnType("integer");

                    b.Property<string>("GameId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Gold")
                        .HasColumnType("integer");

                    b.Property<bool>("IsEliminated")
                        .HasColumnType("boolean");

                    b.Property<int>("Leather")
                        .HasColumnType("integer");

                    b.Property<int>("Mithril")
                        .HasColumnType("integer");

                    b.Property<int>("Mounts")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StartHex")
                        .HasColumnType("text");

                    b.Property<int>("Steel")
                        .HasColumnType("integer");

                    b.Property<int>("TaxRate")
                        .HasColumnType("integer");

                    b.Property<int>("Timber")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("GameId", "Name")
                        .IsUnique();

                    b.ToTable("Nations");
                });

            modelBuilder.Entity("MEPBMmanager.Domain.Entities.NationRelation", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<string>("NationId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TargetNationId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("TargetNationId");

                    b.HasIndex("NationId", "TargetNationId")
                        .IsUnique();

                    b.ToTable("NationRelations");
                });

            modelBuilder.Entity("MEPBMmanager.Domain.Entities.NationTemplate", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Allegiance")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ArcherArmourRank")
                        .HasColumnType("integer");

                    b.Property<int>("ArcherWeaponRank")
                        .HasColumnType("integer");

                    b.Property<string>("BorderTownFortification")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BorderTownName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BorderTownSize")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CapitalFortification")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("CapitalHasHarbour")
                        .HasColumnType("boolean");

                    b.Property<bool>("CapitalHasPort")
                        .HasColumnType("boolean");

                    b.Property<string>("CapitalName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CapitalSize")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Character1Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Character2Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Character3Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Character4Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Character5Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Character6Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("FixedAllegiance")
                        .HasColumnType("boolean");

                    b.Property<string>("GameTypeId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("HCArmourRank")
                        .HasColumnType("integer");

                    b.Property<int>("HCWeaponRank")
                        .HasColumnType("integer");

                    b.Property<int>("HIArmourRank")
                        .HasColumnType("integer");

                    b.Property<int>("HIWeaponRank")
                        .HasColumnType("integer");

                    b.Property<int>("LCArmourRank")
                        .HasColumnType("integer");

                    b.Property<int>("LCWeaponRank")
                        .HasColumnType("integer");

                    b.Property<int>("LIArmourRank")
                        .HasColumnType("integer");

                    b.Property<int>("LIWeaponRank")
                        .HasColumnType("integer");

                    b.Property<int>("MAAArmourRank")
                        .HasColumnType("integer");

                    b.Property<int>("MAAWeaponRank")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("RequiresAdmin")
                        .HasColumnType("boolean");

                    b.Property<string>("StartHex")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("StartingArchers")
                        .HasColumnType("integer");

                    b.Property<int>("StartingBronze")
                        .HasColumnType("integer");

                    b.Property<int>("StartingFood")
                        .HasColumnType("integer");

                    b.Property<int>("StartingGold")
                        .HasColumnType("integer");

                    b.Property<int>("StartingHeavyCavalry")
                        .HasColumnType("integer");

                    b.Property<int>("StartingHeavyInfantry")
                        .HasColumnType("integer");

                    b.Property<int>("StartingLeather")
                        .HasColumnType("integer");

                    b.Property<int>("StartingLightCavalry")
                        .HasColumnType("integer");

                    b.Property<int>("StartingLightInfantry")
                        .HasColumnType("integer");

                    b.Property<int>("StartingMenAtArms")
                        .HasColumnType("integer");

                    b.Property<int>("StartingMithril")
                        .HasColumnType("integer");

                    b.Property<int>("StartingMorale")
                        .HasColumnType("integer");

                    b.Property<int>("StartingMounts")
                        .HasColumnType("integer");

                    b.Property<int>("StartingSteel")
                        .HasColumnType("integer");

                    b.Property<int>("StartingTimber")
                        .HasColumnType("integer");

                    b.Property<int>("StartingTraining")
                        .HasColumnType("integer");

                    b.Property<int>("TaxRate")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("GameTypeId", "Name")
                        .IsUnique();

                    b.ToTable("NationTemplates");
                });

            modelBuilder.Entity("MEPBMmanager.Domain.Entities.Navy", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("CommanderId")
                        .HasColumnType("text");

                    b.Property<string>("LocationHex")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NationId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Strength")
                        .HasColumnType("integer");

                    b.Property<int>("Transports")
                        .HasColumnType("integer");

                    b.Property<int>("Warships")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("NationId");

                    b.ToTable("Navies");
                });

            modelBuilder.Entity("MEPBMmanager.Domain.Entities.Order", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ArmyId")
                        .HasColumnType("text");

                    b.Property<string>("CharacterId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Code")
                        .HasColumnType("integer");

                    b.Property<string>("GameId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NationId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NavyId")
                        .HasColumnType("text");

                    b.Property<string>("Parameters")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PopulationCentreId")
                        .HasColumnType("text");

                    b.Property<string>("Result")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TurnId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ArmyId");

                    b.HasIndex("CharacterId");

                    b.HasIndex("GameId");

                    b.HasIndex("NationId");

                    b.HasIndex("NavyId");

                    b.HasIndex("PopulationCentreId");

                    b.HasIndex("TurnId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("MEPBMmanager.Domain.Entities.Player", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateTime?>("AcceptedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("GameId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsReady")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NationId")
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("WantsToPlayWithUserId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.HasIndex("NationId");

                    b.HasIndex("WantsToPlayWithUserId");

                    b.HasIndex("UserId", "GameId")
                        .IsUnique();

                    b.ToTable("Players");
                });

            modelBuilder.Entity("MEPBMmanager.Domain.Entities.PopulationCentre", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Fortification")
                        .HasColumnType("text");

                    b.Property<bool>("HasHarbour")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasPort")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsCapital")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSieged")
                        .HasColumnType("boolean");

                    b.Property<string>("LocationHex")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Loyalty")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NationId")
                        .HasColumnType("text");

                    b.Property<int>("Production")
                        .HasColumnType("integer");

                    b.Property<string>("Size")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Stores")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("NationId");

                    b.ToTable("PopulationCentres");
                });

            modelBuilder.Entity("MEPBMmanager.Domain.Entities.Role", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("MEPBMmanager.Domain.Entities.Spell", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("CharacterId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsKnown")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsLost")
                        .HasColumnType("boolean");

                    b.Property<int>("Rank")
                        .HasColumnType("integer");

                    b.Property<int>("SpellId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.ToTable("Spells");
                });

            modelBuilder.Entity("MEPBMmanager.Domain.Entities.Turn", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateTime>("Deadline")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GameId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Number")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Season")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("GameId", "Number")
                        .IsUnique();

                    b.ToTable("Turns");
                });

            modelBuilder.Entity("MEPBMmanager.Domain.Entities.TurnResult", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TurnId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("TurnId");

                    b.ToTable("TurnResults");
                });

            modelBuilder.Entity("MEPBMmanager.Domain.Entities.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("MEPBMmanager.Domain.Entities.Army", b =>
                {
                    b.HasOne("MEPBMmanager.Domain.Entities.Nation", "Nation")
                        .WithMany("Armies")
                        .HasForeignKey("NationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Nation");
                });

            modelBuilder.Entity("MEPBMmanager.Domain.Entities.Artifact", b =>
                {
                    b.HasOne("MEPBMmanager.Domain.Entities.Character", "HeldByCharacter")
                        .WithMany("Artifacts")
                        .HasForeignKey("HeldByCharacterId");

                    b.Navigation("HeldByCharacter");
                });

            modelBuilder.Entity("MEPBMmanager.Domain.Entities.Character", b =>
                {
                    b.HasOne("MEPBMmanager.Domain.Entities.Army", "Army")
                        .WithMany("Characters")
                        .HasForeignKey("ArmyId");

                    b.HasOne("MEPBMmanager.Domain.Entities.Company", "Company")
                        .WithMany("Characters")
                        .HasForeignKey("CompanyId");

                    b.HasOne("MEPBMmanager.Domain.Entities.Nation", "Nation")
                        .WithMany("Characters")
                        .HasForeignKey("NationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Army");

                    b.Navigation("Company");

                    b.Navigation("Nation");
                });

            modelBuilder.Entity("MEPBMmanager.Domain.Entities.Company", b =>
                {
                    b.HasOne("MEPBMmanager.Domain.Entities.Nation", "Nation")
                        .WithMany("Companies")
                        .HasForeignKey("NationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Nation");
                });

            modelBuilder.Entity("MEPBMmanager.Domain.Entities.Encounter", b =>
                {
                    b.HasOne("MEPBMmanager.Domain.Entities.Army", "Army")
                        .WithMany("Encounters")
                        .HasForeignKey("ArmyId");

                    b.HasOne("MEPBMmanager.Domain.Entities.Character", "Character")
                        .WithMany("Encounters")
                        .HasForeignKey("CharacterId");

                    b.HasOne("MEPBMmanager.Domain.Entities.Game", "Game")
                        .WithMany("Encounters")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Army");

                    b.Navigation("Character");

                    b.Navigation("Game");
                });

            modelBuilder.Entity("MEPBMmanager.Domain.Entities.Game", b =>
                {
                    b.HasOne("MEPBMmanager.Domain.Entities.GameType", "GameType")
                        .WithMany("Games")
                        .HasForeignKey("GameTypeId");

                    b.Navigation("GameType");
                });

            modelBuilder.Entity("MEPBMmanager.Domain.Entities.GameAdmin", b =>
                {
                    b.HasOne("MEPBMmanager.Domain.Entities.Game", "Game")
                        .WithMany("GameAdmins")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MEPBMmanager.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MEPBMmanager.Domain.Entities.GameEvent", b =>
                {
                    b.HasOne("MEPBMmanager.Domain.Entities.Game", "Game")
                        .WithMany("Events")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MEPBMmanager.Domain.Entities.Turn", "Turn")
                        .WithMany("Events")
                        .HasForeignKey("TurnId");

                    b.Navigation("Game");

                    b.Navigation("Turn");
                });

            modelBuilder.Entity("MEPBMmanager.Domain.Entities.Guard", b =>
                {
                    b.HasOne("MEPBMmanager.Domain.Entities.Character", "Character")
                        .WithMany("GuardedBy")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");
                });

            modelBuilder.Entity("MEPBMmanager.Domain.Entities.HexTile", b =>
                {
                    b.HasOne("MEPBMmanager.Domain.Entities.Game", "Game")
                        .WithMany("HexTiles")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MEPBMmanager.Domain.Entities.GameType", "GameType")
                        .WithMany("HexTiles")
                        .HasForeignKey("GameTypeId");

                    b.Navigation("Game");

                    b.Navigation("GameType");
                });

            modelBuilder.Entity("MEPBMmanager.Domain.Entities.MarketPrice", b =>
                {
                    b.HasOne("MEPBMmanager.Domain.Entities.Game", "Game")
                        .WithMany("MarketPrices")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("MEPBMmanager.Domain.Entities.Message", b =>
                {
                    b.HasOne("MEPBMmanager.Domain.Entities.Game", "Game")
                        .WithMany("Messages")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MEPBMmanager.Domain.Entities.Nation", "Sender")
                        .WithMany("Messages")
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("MEPBMmanager.Domain.Entities.Nation", b =>
                {
                    b.HasOne("MEPBMmanager.Domain.Entities.Game", "Game")
                        .WithMany("Nations")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("MEPBMmanager.Domain.Entities.NationRelation", b =>
                {
                    b.HasOne("MEPBMmanager.Domain.Entities.Nation", "Nation")
                        .WithMany("Relations")
                        .HasForeignKey("NationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MEPBMmanager.Domain.Entities.Nation", "TargetNation")
                        .WithMany("RelationsTo")
                        .HasForeignKey("TargetNationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Nation");

                    b.Navigation("TargetNation");
                });

            modelBuilder.Entity("MEPBMmanager.Domain.Entities.NationTemplate", b =>
                {
                    b.HasOne("MEPBMmanager.Domain.Entities.GameType", "GameType")
                        .WithMany("Templates")
                        .HasForeignKey("GameTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GameType");
                });

            modelBuilder.Entity("MEPBMmanager.Domain.Entities.Navy", b =>
                {
                    b.HasOne("MEPBMmanager.Domain.Entities.Nation", "Nation")
                        .WithMany("Navies")
                        .HasForeignKey("NationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Nation");
                });

            modelBuilder.Entity("MEPBMmanager.Domain.Entities.Order", b =>
                {
                    b.HasOne("MEPBMmanager.Domain.Entities.Army", "Army")
                        .WithMany("Orders")
                        .HasForeignKey("ArmyId");

                    b.HasOne("MEPBMmanager.Domain.Entities.Character", "Character")
                        .WithMany("Orders")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MEPBMmanager.Domain.Entities.Game", "Game")
                        .WithMany("Orders")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MEPBMmanager.Domain.Entities.Nation", "Nation")
                        .WithMany("Orders")
                        .HasForeignKey("NationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MEPBMmanager.Domain.Entities.Navy", "Navy")
                        .WithMany()
                        .HasForeignKey("NavyId");

                    b.HasOne("MEPBMmanager.Domain.Entities.PopulationCentre", null)
                        .WithMany("Orders")
                        .HasForeignKey("PopulationCentreId");

                    b.HasOne("MEPBMmanager.Domain.Entities.Turn", "Turn")
                        .WithMany("Orders")
                        .HasForeignKey("TurnId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Army");

                    b.Navigation("Character");

                    b.Navigation("Game");

                    b.Navigation("Nation");

                    b.Navigation("Navy");

                    b.Navigation("Turn");
                });

            modelBuilder.Entity("MEPBMmanager.Domain.Entities.Player", b =>
                {
                    b.HasOne("MEPBMmanager.Domain.Entities.Game", "Game")
                        .WithMany("Players")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MEPBMmanager.Domain.Entities.Nation", "Nation")
                        .WithMany("Players")
                        .HasForeignKey("NationId");

                    b.HasOne("MEPBMmanager.Domain.Entities.User", "User")
                        .WithMany("Players")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MEPBMmanager.Domain.Entities.User", "WantsToPlayWith")
                        .WithMany()
                        .HasForeignKey("WantsToPlayWithUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Game");

                    b.Navigation("Nation");

                    b.Navigation("User");

                    b.Navigation("WantsToPlayWith");
                });

            modelBuilder.Entity("MEPBMmanager.Domain.Entities.PopulationCentre", b =>
                {
                    b.HasOne("MEPBMmanager.Domain.Entities.Nation", "Nation")
                        .WithMany("PopulationCentres")
                        .HasForeignKey("NationId");

                    b.Navigation("Nation");
                });

            modelBuilder.Entity("MEPBMmanager.Domain.Entities.Spell", b =>
                {
                    b.HasOne("MEPBMmanager.Domain.Entities.Character", "Character")
                        .WithMany("Spells")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");
                });

            modelBuilder.Entity("MEPBMmanager.Domain.Entities.Turn", b =>
                {
                    b.HasOne("MEPBMmanager.Domain.Entities.Game", "Game")
                        .WithMany("Turns")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("MEPBMmanager.Domain.Entities.TurnResult", b =>
                {
                    b.HasOne("MEPBMmanager.Domain.Entities.Turn", "Turn")
                        .WithMany("Results")
                        .HasForeignKey("TurnId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Turn");
                });

            modelBuilder.Entity("MEPBMmanager.Domain.Entities.User", b =>
                {
                    b.HasOne("MEPBMmanager.Domain.Entities.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("MEPBMmanager.Domain.Entities.Army", b =>
                {
                    b.Navigation("Characters");

                    b.Navigation("Encounters");

                    b.Navigation("Orders");
                });

            modelBuilder.Entity("MEPBMmanager.Domain.Entities.Character", b =>
                {
                    b.Navigation("Artifacts");

                    b.Navigation("Encounters");

                    b.Navigation("GuardedBy");

                    b.Navigation("Orders");

                    b.Navigation("Spells");
                });

            modelBuilder.Entity("MEPBMmanager.Domain.Entities.Company", b =>
                {
                    b.Navigation("Characters");
                });

            modelBuilder.Entity("MEPBMmanager.Domain.Entities.Game", b =>
                {
                    b.Navigation("Encounters");

                    b.Navigation("Events");

                    b.Navigation("GameAdmins");

                    b.Navigation("HexTiles");

                    b.Navigation("MarketPrices");

                    b.Navigation("Messages");

                    b.Navigation("Nations");

                    b.Navigation("Orders");

                    b.Navigation("Players");

                    b.Navigation("Turns");
                });

            modelBuilder.Entity("MEPBMmanager.Domain.Entities.GameType", b =>
                {
                    b.Navigation("Games");

                    b.Navigation("HexTiles");

                    b.Navigation("Templates");
                });

            modelBuilder.Entity("MEPBMmanager.Domain.Entities.Nation", b =>
                {
                    b.Navigation("Armies");

                    b.Navigation("Characters");

                    b.Navigation("Companies");

                    b.Navigation("Messages");

                    b.Navigation("Navies");

                    b.Navigation("Orders");

                    b.Navigation("Players");

                    b.Navigation("PopulationCentres");

                    b.Navigation("Relations");

                    b.Navigation("RelationsTo");
                });

            modelBuilder.Entity("MEPBMmanager.Domain.Entities.PopulationCentre", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("MEPBMmanager.Domain.Entities.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("MEPBMmanager.Domain.Entities.Turn", b =>
                {
                    b.Navigation("Events");

                    b.Navigation("Orders");

                    b.Navigation("Results");
                });

            modelBuilder.Entity("MEPBMmanager.Domain.Entities.User", b =>
                {
                    b.Navigation("Players");
                });
#pragma warning restore 612, 618
        }
    }
}
