export const ORDER_ES: Record<number, { name: string; desc: string }> = {
  175: { name: 'Cambiar lealtad', desc: 'Cambia la lealtad de la nación entre Pueblos Libres y Sirvientes Oscuros' },
  180: { name: 'Mejorar relaciones', desc: 'Mejora las relaciones con otra nación' },
  185: { name: 'Empeorar relaciones', desc: 'Empeora las relaciones con otra nación' },
  205: { name: 'Usar artefacto de combate', desc: 'Equipa un artefacto de combate' },
  210: { name: 'Lanzar desafío personal', desc: 'Desafía a otro personaje a un combate singular' },
  215: { name: 'Rechazar todos los desafíos', desc: 'Rechaza todos los desafíos personales de este turno' },
  225: { name: 'Lanzar hechizo de combate', desc: 'Lanza un hechizo durante el combate' },
  230: { name: 'Atacar enemigo', desc: 'Ordena al ejército atacar a un ejército enemigo' },
  235: { name: 'Atacar nación', desc: 'Ordena al ejército atacar a una nación' },
  240: { name: 'Defender', desc: 'Ordena al ejército defender la posición' },
  250: { name: 'Destruir PC', desc: 'Destruye un PC capturado' },
  255: { name: 'Capturar PC', desc: 'Captura un PC' },
  260: { name: 'Asediar PC', desc: 'Pone sitio a un PC' },
  270: { name: 'Destruir barcos', desc: 'Destruye barcos' },
  275: { name: 'Hundir barcos', desc: 'Hunde barcos' },
  280: { name: 'Abandonar barcos', desc: 'Abandona barcos' },
  300: { name: 'Cambiar tasa de impuestos', desc: 'Cambia la tasa nacional de impuestos' },
  340: { name: 'Comida: PC a ejército', desc: 'Transfiere comida del PC al ejército' },
  345: { name: 'Comida: ejército a PC', desc: 'Transfiere comida del ejército al PC' },
  347: { name: 'Comida: ejército a ejército', desc: 'Transfiere comida entre ejércitos' },
  349: { name: 'Máquinas de guerra: ejército a ejército', desc: 'Transfiere máquinas de guerra entre ejércitos' },
  351: { name: 'Armas: ejército a ejército', desc: 'Transfiere armas entre ejércitos' },
  353: { name: 'Armadura: ejército a ejército', desc: 'Transfiere armadura entre ejércitos' },
  355: { name: 'Tropas: ejército a ejército', desc: 'Transfiere tropas entre ejércitos' },
  357: { name: 'Transferir barcos', desc: 'Transfiere barcos entre ubicaciones' },
  370: { name: 'Mejorar armas de la tropa', desc: 'Mejora las armas de las tropas' },
  375: { name: 'Mejorar armadura de la tropa', desc: 'Mejora la armadura de las tropas' },
  400: { name: 'Reclutar caballería pesada', desc: 'Recluta tropas de caballería pesada' },
  404: { name: 'Reclutar caballería ligera', desc: 'Recluta tropas de caballería ligera' },
  408: { name: 'Reclutar infantería pesada', desc: 'Recluta tropas de infantería pesada' },
  412: { name: 'Reclutar infantería ligera', desc: 'Recluta tropas de infantería ligera' },
  416: { name: 'Reclutar arqueros', desc: 'Recluta tropas de arqueros' },
  420: { name: 'Reclutar hombres de armas', desc: 'Recluta tropas de hombres de armas' },
  425: { name: 'Licenciar tropas', desc: 'Licencia tropas del servicio' },
  430: { name: 'Tropas en maniobras', desc: 'Pone a las tropas en maniobras para entrenar' },
  435: { name: 'Ejército en maniobras', desc: 'Pone al ejército en maniobras para entrenar' },
  440: { name: 'Construir máquinas de guerra', desc: 'Construye máquinas de guerra' },
  444: { name: 'Fabricar armadura', desc: 'Fabrica armadura' },
  448: { name: 'Fabricar armas', desc: 'Fabrica armas' },
  452: { name: 'Construir buques de guerra', desc: 'Construye buques de guerra' },
  456: { name: 'Construir transportes', desc: 'Construye barcos de transporte' },
  460: { name: 'Eliminar fondeadero', desc: 'Elimina el fondeadero de un PC' },
  465: { name: 'Eliminar puerto', desc: 'Elimina el puerto de un PC' },
  470: { name: 'Destruir reservas del PC', desc: 'Destruye las reservas de un PC' },
  475: { name: 'Destruir puente', desc: 'Destruye un puente' },
  480: { name: 'Eliminar fortificaciones', desc: 'Elimina las fortificaciones de un PC' },
  490: { name: 'Construir puente', desc: 'Construye un puente en una ubicación' },
  494: { name: 'Fortificar PC', desc: 'Añade fortificaciones a un PC' },
  498: { name: 'Amenazar PC', desc: 'Amenaza un PC para reducir su lealtad' },
  725: { name: 'Nombrar nuevo personaje', desc: 'Crea un nuevo personaje' },
  728: { name: 'Nombrar nuevo comandante', desc: 'Crea un nuevo personaje comandante' },
  745: { name: 'Crear compañía', desc: 'Crea una nueva compañía' },
  750: { name: 'Disolver compañía', desc: 'Disuelve una compañía' },
  770: { name: 'Contratar ejército', desc: 'Contrata un nuevo ejército' },
  775: { name: 'Disolver ejército', desc: 'Disuelve un ejército' },
  780: { name: 'Transferir mando', desc: 'Transfiere el mando a otro personaje' },
  925: { name: 'Reconocer área', desc: 'Reconoce el área circundante' },
  950: { name: 'Trasladar capital', desc: 'Traslada la capital nacional' },
  600: { name: 'Contraespionaje', desc: 'Contrarresta las operaciones de espionaje enemigas' },
  605: { name: 'Vigilar ubicación', desc: 'Vigila una ubicación contra agentes enemigos' },
  610: { name: 'Proteger personaje', desc: 'Protege a un personaje contra asesinatos' },
  615: { name: 'Asesinar personaje', desc: 'Intenta asesinar a un personaje' },
  620: { name: 'Secuestrar personaje', desc: 'Intenta secuestrar a un personaje' },
  625: { name: 'Liberar rehén', desc: 'Libera a un rehén' },
  630: { name: 'Rescatar rehén', desc: 'Rescata a un rehén del cautiverio' },
  635: { name: 'Interrogar rehén', desc: 'Interroga a un rehén para obtener información' },
  640: { name: 'Tomar custodia del rehén', desc: 'Toma la custodia de un rehén' },
  645: { name: 'Encarcelar rehén', desc: 'Encarcela a un rehén' },
  650: { name: 'Ejecutar rehén', desc: 'Ejecuta a un rehén' },
  655: { name: 'Exigir rescate', desc: 'Exige un rescate por un rehén' },
  665: { name: 'Sabotear puente', desc: 'Sabotea un puente' },
  670: { name: 'Sabotear fortificaciones', desc: 'Sabotea fortificaciones' },
  675: { name: 'Sabotear fondeadero/puerto', desc: 'Sabotea un fondeadero o puerto' },
  680: { name: 'Sabotear producción', desc: 'Sabotea las reservas de producción' },
  685: { name: 'Robar artefacto', desc: 'Intenta robar un artefacto' },
  690: { name: 'Robar oro', desc: 'Intenta robar oro' },
  731: { name: 'Nombrar nuevo agente', desc: 'Crea un nuevo personaje agente' },
  905: { name: 'Explorar ejército', desc: 'Explora un ejército enemigo' },
  910: { name: 'Explorar área', desc: 'Explora el área circundante' },
  915: { name: 'Explorar hex', desc: 'Explora un hex concreto' },
  920: { name: 'Explorar PC', desc: 'Explora un PC' },
  930: { name: 'Explorar personajes', desc: 'Explora personajes enemigos' },
  500: { name: 'Reclutar agente doble', desc: 'Recluta un agente doble' },
  505: { name: 'Sobornar/influir personaje', desc: 'Soborna o influye a un personaje' },
  520: { name: 'Influir lealtad de PC propio', desc: 'Influye en la lealtad de tu propio PC' },
  525: { name: 'Influir lealtad de PC ajeno', desc: 'Influye en la lealtad del PC de otra nación' },
  530: { name: 'Mejorar fondeadero a puerto', desc: 'Mejora un fondeadero a puerto' },
  535: { name: 'Añadir fondeadero al PC', desc: 'Añade un fondeadero a un PC' },
  550: { name: 'Mejorar PC', desc: 'Mejora un PC' },
  552: { name: 'Establecer campamento', desc: 'Establece un campamento en la ubicación actual' },
  555: { name: 'Crear campamento', desc: 'Crea un nuevo campamento' },
  560: { name: 'Abandonar campamento', desc: 'Abandona un campamento' },
  565: { name: 'Reducir PC', desc: 'Reduce el tamaño de un PC' },
  580: { name: 'Difundir rumores', desc: 'Difunde rumores para afectar la lealtad' },
  585: { name: 'Descubrir secretos', desc: 'Descubre información oculta' },
  734: { name: 'Nombrar nuevo emisario', desc: 'Crea un nuevo personaje emisario' },
  949: { name: 'Transferir propiedad', desc: 'Transfiere la propiedad de un PC' },
  120: { name: 'Lanzar hechizo de curación', desc: 'Lanza un hechizo de curación sobre un personaje' },
  330: { name: 'Lanzar hechizo de invocación', desc: 'Lanza un hechizo de invocación' },
  700: { name: 'Olvidar hechizo', desc: 'Olvida un hechizo conocido' },
  705: { name: 'Investigar hechizo', desc: 'Investiga un nuevo hechizo' },
  710: { name: 'Formar aprendiz de mago', desc: 'Entrena a un mago aprendiz' },
  737: { name: 'Nombrar nuevo mago', desc: 'Crea un nuevo personaje mago' },
  940: { name: 'Lanzar hechizo de conocimiento', desc: 'Lanza un hechizo de conocimiento para obtener información' },
  810: { name: 'Mover personaje', desc: 'Mueve un personaje a una nueva ubicación' },
  820: { name: 'Mover compañía', desc: 'Mueve una compañía a una nueva ubicación' },
  825: { name: 'Lanzar hechizo de movimiento', desc: 'Lanza un hechizo de movimiento' },
  830: { name: 'Mover armada', desc: 'Mueve una unidad naval' },
  840: { name: 'Mantener posición', desc: 'Mantiene la posición y la defiende' },
  850: { name: 'Mover ejército', desc: 'Mueve un ejército a una nueva ubicación' },
  860: { name: 'Marcha forzada del ejército', desc: 'Marcha forzada de un ejército (más rápido pero con pérdida de moral)' },
  870: { name: 'Mover personaje y unirse al ejército', desc: 'Mueve el personaje y se une a un ejército' },
  310: { name: 'Pujar a caravanas', desc: 'Puja por mercancías de las caravanas' },
  315: { name: 'Comprar a caravanas', desc: 'Compra mercancías a precio de mercado' },
  320: { name: 'Vender a caravanas', desc: 'Vende mercancías a precio de mercado' },
  325: { name: 'Venta nacional a caravanas', desc: 'Orden de venta nacional' },
  285: { name: 'Reacción a encuentro', desc: 'Reacciona a un encuentro' },
  290: { name: 'Investigar encuentro', desc: 'Investiga un encuentro' },
  360: { name: 'Transferir: artefactos', desc: 'Transfiere artefactos entre personajes' },
  363: { name: 'Transferir: rehenes', desc: 'Transfiere rehenes entre personajes' },
  660: { name: 'Ofrecer rescate', desc: 'Ofrece un rescate por un rehén' },
  740: { name: 'Retirar personaje', desc: 'Retira a un personaje' },
  755: { name: 'Unirse a compañía', desc: 'Se une a una compañía' },
  760: { name: 'Dejar compañía', desc: 'Deja una compañía' },
  765: { name: 'Dividir ejército', desc: 'Divide un ejército en dos' },
  785: { name: 'Unirse al ejército', desc: 'Se une a un ejército' },
  790: { name: 'Dejar el ejército', desc: 'Deja un ejército' },
  792: { name: 'Soltar artefacto', desc: 'Suelta un artefacto' },
  794: { name: 'Anclar barcos', desc: 'Ancla barcos en un puerto' },
  796: { name: 'Recoger artefacto', desc: 'Recoge un artefacto' },
  798: { name: 'Recoger barcos', desc: 'Recoge barcos' },
  805: { name: 'Usar artefacto de movimiento', desc: 'Usa un artefacto de movimiento' },
  900: { name: 'Buscar artefacto', desc: 'Busca un artefacto' },
  935: { name: 'Usar artefacto de adivinación', desc: 'Usa un artefacto de adivinación' },
  942: { name: 'Mover mapa de turno', desc: 'Mueve el mapa de turno (Cuarta Edad)' },
  945: { name: 'Usar artefacto de ocultación', desc: 'Usa un artefacto de ocultación' },
  947: { name: 'Transporte nacional', desc: 'Transporta mercancías a nivel nacional' },
  948: { name: 'Transporte por caravana', desc: 'Transporta mercancías por caravana' },
  960: { name: 'Subir precios de caravanas', desc: 'Sube los precios de las caravanas' },
  965: { name: 'Bajar precios de caravanas', desc: 'Baja los precios de las caravanas' },
  990: { name: 'El Anillo Único', desc: 'Intenta usar el Anillo Único' },
};
export const ORDER_HELP_ES: Record<number, string> = {
  175: 'Cambia el bando de tu nación. Elige con cuidado.',
  180: 'Mejora las relaciones con otra nación.',
  185: 'Empeora las relaciones con otra nación.',
  205: 'Equipa un artefacto de tipo arma que lleves (+mando).',
  210: 'Duelo a muerte salvo rechazo. El ganador gana habilidad y cambia la moral.',
  215: 'Rechaza todos los desafíos de este turno; un comandante puede perder moral.',
  225: 'Requiere un hechizo de combate conocido. Se aplica en su batalla. +1 habilidad de mago.',
  230: 'Ataca a todo lo que haya en el hex. Ganador: +1 mando, +2 entrenamiento.',
  235: 'Ataca a las fuerzas de una nación en el hex. Ganador: +1 mando, +2 entrenamiento.',
  240: '+5 moral, +1 entrenamiento. Mantiene la posición, sin atacar.',
  250: 'Asalta el PC en el hex para destruirlo.',
  255: 'Asalta el PC en el hex para capturarlo.',
  260: 'Marca asedio: lealtad -20. Aún sin asalto.',
  270: 'Destruye los buques de guerra de tu primera armada. +1 mando.',
  275: 'Hunde los transportes de tu primera armada.',
  280: 'Abandona todos los barcos de tu primera armada.',
  300: 'Limitado a 10-80. La lealtad varía según la tasa de impuestos.',
  340: 'Mueve comida de la reserva nacional al ejército.',
  345: 'Mueve comida del ejército a la reserva nacional.',
  347: 'Mueve comida entre tus ejércitos.',
  349: 'Mueve máquinas de guerra entre tus ejércitos.',
  351: 'Mueve niveles de armas entre tus ejércitos.',
  353: 'Mueve niveles de armadura entre tus ejércitos.',
  355: 'Mueve tropas (los 6 tipos) entre tus ejércitos.',
  357: 'Aún no implementado: solo mensaje.',
  370: 'Un solo material; fija los tipos asignados a su nivel. Muestra el coste en oro y material en vivo.',
  375: 'Un solo material; fija los tipos asignados a su nivel. Muestra el coste en oro y material en vivo.',
  400: 'La caballería cuesta monturas. Limitado por capacidad del PC, oro y monturas.',
  404: 'La caballería cuesta monturas. Limitado por capacidad del PC, oro y monturas.',
  408: 'Limitado por capacidad del PC y oro.',
  412: 'Limitado por capacidad del PC y oro.',
  416: 'Limitado por capacidad del PC y oro.',
  420: 'Limitado por capacidad del PC y oro.',
  425: 'Licencia tropas por 10 de oro cada una.',
  430: '+5 moral, +1 mando.',
  435: '+10 moral, +1 mando.',
  440: '50 de oro + 10 madera + 5 acero cada una. Requiere PC propio en el ejército.',
  444: 'Sube los niveles de armadura hacia 100. 5 de oro + 5 cuero + 2 acero por punto.',
  448: 'Sube los niveles de armas hacia 100. 5 de oro + 3 bronce + 1 acero por punto.',
  452: '1000 de oro + madera cada uno. Requiere PC costero propio con puerto/fondeadero.',
  456: '1000 de oro + madera cada uno. Requiere PC costero propio con puerto/fondeadero.',
  460: 'Elimina el fondeadero.',
  465: 'Elimina el puerto.',
  470: 'Destruye las reservas del PC.',
  475: 'Requiere mando o PC propio en el hex; la tirada decide.',
  480: 'Elimina las fortificaciones.',
  490: 'Requiere río; los ríos grandes necesitan camino. Madera + oro mostrados en vivo.',
  494: 'Un nivel por turno. La madera sale de las reservas del PC.',
  498: 'Baja la lealtad sin atacar.',
  725: 'Crea un nuevo personaje (pide un nombre).',
  728: 'Crea un nuevo comandante (pide un nombre).',
  745: 'Crea una compañía por 500 de oro.',
  750: 'Disuelve la compañía del personaje.',
  770: 'Contrata un ejército nuevo en la capital.',
  775: 'Disuelve el ejército.',
  780: 'Transfiere el mando del ejército. -5 moral.',
  925: 'Reconoce el área (tirada simplificada por ahora).',
  950: 'Traslada la capital. 25000 de oro.',
  600: 'Contraespionaje (tirada simplificada por ahora).',
  605: 'Vigila una ubicación contra agentes enemigos.',
  610: 'Protege a un personaje contra asesinatos.',
  615: 'Mata al objetivo. Objetivos del mismo bando permitidos bajo tu riesgo.',
  620: 'El objetivo debe estar vivo y libre.',
  625: 'El objetivo debe ser un rehén.',
  630: 'El objetivo debe ser un rehén.',
  635: 'El objetivo debe ser un rehén.',
  640: 'El objetivo debe ser un rehén.',
  645: 'El objetivo debe ser un rehén.',
  650: 'El objetivo debe ser un rehén.',
  655: 'El objetivo debe ser un rehén.',
  665: 'Requiere puente en el hex.',
  670: 'Degrada las fortificaciones del PC.',
  675: 'Elimina el fondeadero/puerto del PC.',
  680: 'Destruye reservas y -50 producción en el PC.',
  685: 'Roba el artefacto para tu nación.',
  690: 'Roba oro de la nación víctima.',
  731: 'Crea un nuevo agente (pide un nombre).',
  905: 'Explora los ejércitos en el hex.',
  910: 'Explora el área (tirada simplificada por ahora).',
  915: 'Explora un hex (tirada simplificada por ahora).',
  920: 'Explora el PC.',
  930: 'Explora los personajes en el hex.',
  500: 'Coloca un espía en UNA nación. Solo un agente activo por nación.',
  505: 'Solo recluta de naciones no jugadas del mismo bando (<21 personajes); si no, un agente sobornado con información. Mínimo 500 de oro, más oro mejora las opciones.',
  520: 'Sube la lealtad de tu propio PC.',
  525: 'Baja la lealtad extranjera y deja las relaciones neutrales en ambos sentidos.',
  530: 'Fondeadero a puerto: 1500 de oro + 2500 madera.',
  535: 'Nuevo fondeadero: 2500 de oro + 5000 madera.',
  550: 'Mejora el PC un nivel.',
  552: 'Asienta un campamento por 4000 de oro. Un nombre vacío elige de tu reserva nacional.',
  555: 'Crea un campamento por 2000 de oro. Un nombre vacío elige de tu reserva nacional.',
  560: 'Abandona tu campamento aquí.',
  565: 'Reduce el PC un nivel, -20 lealtad.',
  580: 'Siembra rumores falsos (diseño pendiente, ver rumores_580_585.txt).',
  585: 'Descubre secretos y rumores (diseño pendiente, ver rumores_580_585.txt).',
  734: 'Crea un nuevo emisario (pide un nombre).',
  949: 'Transfiere la propiedad del PC a tu nación.',
  120: 'Requiere un hechizo de curación conocido válido. El objetivo opcional debe compartir el hex. +1 habilidad de mago si tiene éxito.',
  330: 'Requiere un hechizo de invocación conocido válido. +1 habilidad de mago si tiene éxito.',
  700: 'Olvida un hechizo conocido.',
  705: 'Aprende un hechizo nuevo (aleatorio si se deja vacío). Empieza en rango 0.',
  710: 'Entrena al mago: +2 si tiene éxito.',
  737: 'Crea un nuevo mago (pide un nombre).',
  940: 'El objetivo depende del hechizo: personaje, nación, artefacto, PC, ejército o hex. +1 habilidad de mago si tiene éxito.',
  810: 'Mueve dentro de un presupuesto de 14 MP. Evasivo cuesta el doble.',
  820: 'Mueve la compañía.',
  825: 'Requiere un hechizo de movimiento conocido válido. Teletransporta la fuerza.',
  830: 'Mueve la armada (1 MP en mar abierto). Riesgo de tormenta.',
  840: 'Mantiene la posición.',
  850: 'Mueve el ejército dentro del presupuesto.',
  860: 'Marcha más larga, pérdida de moral. Las naciones resistentes pierden menos.',
  870: 'Mueve y se une al ejército en el destino.',
  310: 'Puja a precios de caravana. Los precios de mercado son fijos por ahora.',
  315: 'Compra a precios de caravana. Los precios de mercado son fijos por ahora.',
  320: 'Vende reservas por oro. Límite de 20000 de oro por turno.',
  325: 'Vende un porcentaje de las reservas. Límite de 20000 de oro por turno.',
  285: 'Reacciona a un encuentro conocido aquí.',
  290: 'Investiga rumores y encuentros en el hex.',
  360: 'Mueve un artefacto entre personajes.',
  363: 'Mueve un rehén. El objetivo debe estar secuestrado.',
  660: 'Ofrece un rescate.',
  740: 'Retira al personaje.',
  755: 'Se une a una compañía de tu nación.',
  760: 'Deja la compañía.',
  765: 'Divide el ejército por la mitad.',
  785: 'Se une al ejército (también se mueve hasta allí).',
  790: 'Deja el ejército.',
  792: 'Suelta el artefacto en el hex.',
  794: 'Ancla los barcos en la ubicación.',
  796: 'Recoge un artefacto.',
  798: 'Recoge barcos en la ubicación.',
  805: 'Usa un artefacto de movimiento que lleves.',
  900: 'Busca un artefacto.',
  935: 'Usa un artefacto de adivinación que lleves.',
  942: 'Solo Cuarta Edad.',
  945: 'Usa un artefacto de ocultación que lleves.',
  947: 'No implementado: crea recursos (provisional).',
  948: 'No implementado: crea recursos (provisional).',
  960: 'Solo Cuarta Edad, aún sin handler.',
  965: 'Solo Cuarta Edad, aún sin handler.',
  990: 'Provisional: solo d6, aún sin lógica del Anillo.',
};
