import { OrderDefinition } from '../types/orders';

export const ORDER_DEFINITIONS: OrderDefinition[] = [
  // COMMAND SKILL ORDERS
  { code: 175, abbreviation: 'ChAlleg', name: 'Change Allegiance', restrictions: ['c', 'cap'], difficulty: 'average', skillIncrease: false, description: 'Change nation allegiance between Free Peoples and Dark Servants' },
  { code: 180, abbreviation: 'UpStNat', name: 'Upgrade Relations', restrictions: ['c', 'cap'], difficulty: 'easy', skillIncrease: false, description: 'Improve relations with another nation' },
  { code: 185, abbreviation: 'DnStNat', name: 'Downgrade Relations', restrictions: ['c', 'cap'], difficulty: 'easy', skillIncrease: false, description: 'Worsen relations with another nation' },
  { code: 205, abbreviation: 'UsCbArt', name: 'Use Combat Artifact', restrictions: [], difficulty: 'automatic', skillIncrease: false, description: 'Equip a combat artifact' },
  { code: 210, abbreviation: 'IssPers', name: 'Issue Personal Challenge', restrictions: [], difficulty: 'automatic', skillIncrease: true, description: 'Challenge another character to single combat' },
  { code: 215, abbreviation: 'RfsPers', name: 'Refuse All Challenges', restrictions: [], difficulty: 'automatic', skillIncrease: false, description: 'Refuse all personal challenges this turn' },
  { code: 225, abbreviation: 'CstCbSp', name: 'Cast Combat Spell', restrictions: ['m'], difficulty: 'varies', skillIncrease: true, description: 'Cast a spell during combat' },
  { code: 230, abbreviation: 'AttEnmy', name: 'Attack Enemy', restrictions: ['c', 'com'], difficulty: 'automatic', skillIncrease: true, description: 'Order army to attack an enemy army' },
  { code: 235, abbreviation: 'AttNat', name: 'Attack Nation', restrictions: ['c', 'com'], difficulty: 'automatic', skillIncrease: true, description: 'Order army to attack a nation' },
  { code: 240, abbreviation: 'Defend', name: 'Defend', restrictions: ['c', 'com'], difficulty: 'automatic', skillIncrease: true, description: 'Order army to defend position' },
  { code: 250, abbreviation: 'DstPop', name: 'Destroy Population Centre', restrictions: ['c', 'com'], difficulty: 'automatic', skillIncrease: true, description: 'Destroy a captured population centre' },
  { code: 255, abbreviation: 'CptrPop', name: 'Capture Population Centre', restrictions: ['c', 'com'], difficulty: 'automatic', skillIncrease: true, description: 'Capture a population centre' },
  { code: 260, abbreviation: 'SiegPop', name: 'Siege Population Centre', restrictions: ['c', 'com'], difficulty: 'average', skillIncrease: true, description: 'Lay siege to a population centre' },
  { code: 270, abbreviation: 'DstShp', name: 'Destroy Ships', restrictions: ['c', 'com'], difficulty: 'automatic', skillIncrease: false, description: 'Destroy ships' },
  { code: 275, abbreviation: 'ScttShp', name: 'Scuttle Ships', restrictions: ['c', 'com'], difficulty: 'automatic', skillIncrease: false, description: 'Scuttle ships' },
  { code: 280, abbreviation: 'AbanShp', name: 'Abandon Ships', restrictions: ['c', 'cap'], difficulty: 'automatic', skillIncrease: false, description: 'Abandon ships' },
  { code: 300, abbreviation: 'ChTaxRt', name: 'Change Tax Rate', restrictions: ['c', 'cap'], difficulty: 'easy', skillIncrease: false, description: 'Change the national tax rate' },
  { code: 340, abbreviation: 'TrPo2Ar', name: 'Food: PC to Army', restrictions: ['c'], difficulty: 'automatic', skillIncrease: false, description: 'Transfer food from population centre to army' },
  { code: 345, abbreviation: 'TrAr2Po', name: 'Food: Army to PC', restrictions: ['c'], difficulty: 'automatic', skillIncrease: false, description: 'Transfer food from army to population centre' },
  { code: 347, abbreviation: 'TrFood', name: 'Food: Army to Army', restrictions: ['c'], difficulty: 'automatic', skillIncrease: false, description: 'Transfer food between armies' },
  { code: 349, abbreviation: 'TrWarMa', name: 'War Machines: Army-Army', restrictions: ['c'], difficulty: 'automatic', skillIncrease: false, description: 'Transfer war machines between armies' },
  { code: 351, abbreviation: 'TrWpns', name: 'Weapons: Army to Army', restrictions: ['c'], difficulty: 'automatic', skillIncrease: false, description: 'Transfer weapons between armies' },
  { code: 353, abbreviation: 'TrArmr', name: 'Armour: Army to Army', restrictions: ['c'], difficulty: 'automatic', skillIncrease: false, description: 'Transfer armour between armies' },
  { code: 355, abbreviation: 'TrTrps', name: 'Troops: Army to Army', restrictions: ['c'], difficulty: 'automatic', skillIncrease: false, description: 'Transfer troops between armies' },
  { code: 357, abbreviation: 'TrShp', name: 'Transfer Ships', restrictions: ['c'], difficulty: 'automatic', skillIncrease: false, description: 'Transfer ships between locations' },
  { code: 370, abbreviation: 'UpWpns', name: 'Upgrade Troop Weapons', restrictions: ['c'], difficulty: 'automatic', skillIncrease: false, description: 'Upgrade weapons for troops' },
  { code: 375, abbreviation: 'UpArmr', name: 'Upgrade Troop Armour', restrictions: ['c'], difficulty: 'automatic', skillIncrease: false, description: 'Upgrade armour for troops' },
  { code: 400, abbreviation: 'HvCvlry', name: 'Recruit Heavy Cavalry', restrictions: ['c'], difficulty: 'automatic', skillIncrease: false, description: 'Recruit heavy cavalry troops' },
  { code: 404, abbreviation: 'LtCvlry', name: 'Recruit Light Cavalry', restrictions: ['c'], difficulty: 'automatic', skillIncrease: false, description: 'Recruit light cavalry troops' },
  { code: 408, abbreviation: 'HvInfan', name: 'Recruit Heavy Infantry', restrictions: ['c'], difficulty: 'automatic', skillIncrease: false, description: 'Recruit heavy infantry troops' },
  { code: 412, abbreviation: 'LtInfan', name: 'Recruit Light Infantry', restrictions: ['c'], difficulty: 'automatic', skillIncrease: false, description: 'Recruit light infantry troops' },
  { code: 416, abbreviation: 'Archers', name: 'Recruit Archers', restrictions: ['c'], difficulty: 'automatic', skillIncrease: false, description: 'Recruit archer troops' },
  { code: 420, abbreviation: 'MenAtAr', name: 'Recruit Men-at-Arms', restrictions: ['c'], difficulty: 'automatic', skillIncrease: false, description: 'Recruit men-at-arms troops' },
  { code: 425, abbreviation: 'RtrTrps', name: 'Retire Troops', restrictions: ['c'], difficulty: 'automatic', skillIncrease: false, description: 'Retire troops from service' },
  { code: 430, abbreviation: 'TrpsMan', name: 'Troops on Manoeuvres', restrictions: ['c'], difficulty: 'automatic', skillIncrease: true, description: 'Put troops on manoeuvres for training' },
  { code: 435, abbreviation: 'ArmyMan', name: 'Army on Manoeuvres', restrictions: ['c', 'com'], difficulty: 'automatic', skillIncrease: true, description: 'Put army on manoeuvres for training' },
  { code: 440, abbreviation: 'MakWrMa', name: 'Make War Machines', restrictions: ['c'], difficulty: 'automatic', skillIncrease: false, description: 'Construct war machines' },
  { code: 444, abbreviation: 'MakArmr', name: 'Make Armour', restrictions: ['c'], difficulty: 'automatic', skillIncrease: false, description: 'Construct armour' },
  { code: 448, abbreviation: 'MakWpns', name: 'Make Weapons', restrictions: ['c'], difficulty: 'automatic', skillIncrease: false, description: 'Construct weapons' },
  { code: 452, abbreviation: 'MakWShp', name: 'Make Warships', restrictions: ['c'], difficulty: 'automatic', skillIncrease: false, description: 'Construct warships' },
  { code: 456, abbreviation: 'MakTShp', name: 'Make Transports', restrictions: ['c'], difficulty: 'automatic', skillIncrease: false, description: 'Construct transport ships' },
  { code: 460, abbreviation: 'RmvHar', name: 'Remove Harbour', restrictions: ['c'], difficulty: 'easy', skillIncrease: false, description: 'Remove a harbour from a population centre' },
  { code: 465, abbreviation: 'RmvPort', name: 'Remove Port', restrictions: ['c'], difficulty: 'easy', skillIncrease: false, description: 'Remove a port from a population centre' },
  { code: 470, abbreviation: 'DstStor', name: 'Destroy PC Stores', restrictions: ['c'], difficulty: 'average', skillIncrease: false, description: 'Destroy stores at a population centre' },
  { code: 475, abbreviation: 'DstBrdg', name: 'Destroy Bridge', restrictions: ['c'], difficulty: 'average', skillIncrease: false, description: 'Destroy a bridge' },
  { code: 480, abbreviation: 'RmvFort', name: 'Remove Fortifications', restrictions: ['c'], difficulty: 'hard', skillIncrease: false, description: 'Remove fortifications from a population centre' },
  { code: 490, abbreviation: 'BldBrdg', name: 'Build Bridge', restrictions: ['c'], difficulty: 'average', skillIncrease: false, description: 'Build a bridge at a location' },
  { code: 494, abbreviation: 'FortPop', name: 'Fortify Population Centre', restrictions: ['c'], difficulty: 'average', skillIncrease: true, description: 'Add fortifications to a population centre' },
  { code: 498, abbreviation: 'Threat', name: 'Threaten Population Centre', restrictions: ['c', 'com'], difficulty: 'hard', skillIncrease: true, description: 'Threaten a population centre to reduce loyalty' },
  { code: 725, abbreviation: 'NamChar', name: 'Name New Character', restrictions: ['c', 'cap'], difficulty: 'automatic', skillIncrease: false, description: 'Create a new character' },
  { code: 728, abbreviation: 'NamComm', name: 'Name New Commander', restrictions: ['c', 'cap'], difficulty: 'automatic', skillIncrease: false, description: 'Create a new commander character' },
  { code: 745, abbreviation: 'CreCmpy', name: 'Create Company', restrictions: ['c', 'without'], difficulty: 'automatic', skillIncrease: false, description: 'Create a new company' },
  { code: 750, abbreviation: 'DsbCmpy', name: 'Disband Company', restrictions: ['c', 'company'], difficulty: 'automatic', skillIncrease: false, description: 'Disband a company' },
  { code: 770, abbreviation: 'HrArmy', name: 'Hire Army', restrictions: ['c', 'without'], difficulty: 'automatic', skillIncrease: false, description: 'Hire a new army' },
  { code: 775, abbreviation: 'DsbArmy', name: 'Disband Army', restrictions: ['c'], difficulty: 'automatic', skillIncrease: false, description: 'Disband an army' },
  { code: 780, abbreviation: 'TrComm', name: 'Transfer Command', restrictions: ['c', 'com', 'company'], difficulty: 'automatic', skillIncrease: false, description: 'Transfer command to another character' },
  { code: 925, abbreviation: 'Recon', name: 'Recon Area', restrictions: ['c'], difficulty: 'easy', skillIncrease: false, description: 'Reconnoitre the surrounding area' },
  { code: 950, abbreviation: 'ReloCap', name: 'Relocate Capital', restrictions: ['c', 'cap'], difficulty: 'easy', skillIncrease: false, description: 'Relocate the national capital' },

  // AGENT SKILL ORDERS
  { code: 600, abbreviation: 'CntrEsp', name: 'Counter Espionage', restrictions: ['a'], difficulty: 'average', skillIncrease: true, description: 'Counter enemy espionage operations' },
  { code: 605, abbreviation: 'GrdLoc', name: 'Guard Location', restrictions: ['a'], difficulty: 'automatic', skillIncrease: true, description: 'Guard a location against enemy agents' },
  { code: 610, abbreviation: 'GrdChar', name: 'Guard Character', restrictions: ['a'], difficulty: 'automatic', skillIncrease: true, description: 'Guard a character against assassination' },
  { code: 615, abbreviation: 'Assass', name: 'Assassinate Character', restrictions: ['a'], difficulty: 'hard', skillIncrease: true, description: 'Attempt to assassinate a character' },
  { code: 620, abbreviation: 'Kidnap', name: 'Kidnap Character', restrictions: ['a'], difficulty: 'hard', skillIncrease: true, description: 'Attempt to kidnap a character' },
  { code: 625, abbreviation: 'Release', name: 'Release Hostage', restrictions: ['a'], difficulty: 'automatic', skillIncrease: false, description: 'Release a hostage' },
  { code: 630, abbreviation: 'Rescue', name: 'Rescue Hostage', restrictions: ['a'], difficulty: 'hard', skillIncrease: true, description: 'Rescue a hostage from captivity' },
  { code: 635, abbreviation: 'Interr', name: 'Interrogate Hostage', restrictions: ['a'], difficulty: 'average', skillIncrease: true, description: 'Interrogate a hostage for information' },
  { code: 640, abbreviation: 'Custody', name: 'Take Custody of Hostage', restrictions: ['a'], difficulty: 'automatic', skillIncrease: false, description: 'Take custody of a hostage' },
  { code: 645, abbreviation: 'Imprsn', name: 'Imprison Hostage', restrictions: ['a'], difficulty: 'automatic', skillIncrease: false, description: 'Imprison a hostage' },
  { code: 650, abbreviation: 'Execute', name: 'Execute Hostage', restrictions: ['a'], difficulty: 'automatic', skillIncrease: false, description: 'Execute a hostage' },
  { code: 655, abbreviation: 'RansDmd', name: 'Demand Ransom', restrictions: ['a'], difficulty: 'automatic', skillIncrease: false, description: 'Demand ransom for a hostage' },
  { code: 665, abbreviation: 'SabBrdg', name: 'Sabotage Bridge', restrictions: ['a'], difficulty: 'hard', skillIncrease: true, description: 'Sabotage a bridge' },
  { code: 670, abbreviation: 'SabFort', name: 'Sabotage Fortifications', restrictions: ['a'], difficulty: 'hard', skillIncrease: true, description: 'Sabotage fortifications' },
  { code: 675, abbreviation: 'SabPort', name: 'Sabotage Harbour/Port', restrictions: ['a'], difficulty: 'hard', skillIncrease: true, description: 'Sabotage a harbour or port' },
  { code: 680, abbreviation: 'SabStor', name: 'Sabotage Production', restrictions: ['a'], difficulty: 'hard', skillIncrease: true, description: 'Sabotage production stores' },
  { code: 685, abbreviation: 'StlArt', name: 'Steal Artifact', restrictions: ['a'], difficulty: 'hard', skillIncrease: true, description: 'Attempt to steal an artifact' },
  { code: 690, abbreviation: 'StlGold', name: 'Steal Gold', restrictions: ['a'], difficulty: 'hard', skillIncrease: true, description: 'Attempt to steal gold' },
  { code: 731, abbreviation: 'NamAgen', name: 'Name New Agent', restrictions: ['a', 'cap'], difficulty: 'automatic', skillIncrease: false, description: 'Create a new agent character' },
  { code: 905, abbreviation: 'ScoArmy', name: 'Scout Army', restrictions: ['a'], difficulty: 'average', skillIncrease: false, description: 'Scout an enemy army' },
  { code: 910, abbreviation: 'ScoArea', name: 'Scout Area', restrictions: ['a'], difficulty: 'automatic', skillIncrease: false, description: 'Scout the surrounding area' },
  { code: 915, abbreviation: 'ScoHex', name: 'Scout Hex', restrictions: ['a'], difficulty: 'easy', skillIncrease: false, description: 'Scout a specific hex' },
  { code: 920, abbreviation: 'ScoPop', name: 'Scout Population Centre', restrictions: ['a'], difficulty: 'easy', skillIncrease: false, description: 'Scout a population centre' },
  { code: 930, abbreviation: 'ScoChar', name: 'Scout for Characters', restrictions: ['a'], difficulty: 'average', skillIncrease: false, description: 'Scout for enemy characters' },

  // EMISSARY SKILL ORDERS
  { code: 500, abbreviation: 'Double', name: 'Recruit Double Agent', restrictions: ['e'], difficulty: 'average', skillIncrease: true, description: 'Recruit a double agent' },
  { code: 505, abbreviation: 'Bribe', name: 'Bribe/Influence Character', restrictions: ['e'], difficulty: 'average', skillIncrease: true, description: 'Bribe or influence a character' },
  { code: 520, abbreviation: 'InfYour', name: 'Influence Your PC Loyalty', restrictions: ['e'], difficulty: 'automatic', skillIncrease: true, description: 'Influence loyalty of your own population centre' },
  { code: 525, abbreviation: 'InfOthr', name: 'Influence Others PC Loyalty', restrictions: ['e'], difficulty: 'average', skillIncrease: true, description: 'Influence loyalty of another nation population centre' },
  { code: 530, abbreviation: 'Har2Por', name: 'Improve Harbour to Port', restrictions: ['e'], difficulty: 'easy', skillIncrease: false, description: 'Improve a harbour to a port' },
  { code: 535, abbreviation: 'AddHar', name: 'Add Harbour to PC', restrictions: ['e'], difficulty: 'easy', skillIncrease: false, description: 'Add a harbour to a population centre' },
  { code: 550, abbreviation: 'ImprPop', name: 'Improve Population Centre', restrictions: ['e'], difficulty: 'average', skillIncrease: true, description: 'Improve a population centre' },
  { code: 552, abbreviation: 'PosCmp', name: 'Post Camp', restrictions: ['c', 'com'], difficulty: 'average', skillIncrease: false, description: 'Post a camp at current location' },
  { code: 555, abbreviation: 'CreCmp', name: 'Create Camp', restrictions: ['e'], difficulty: 'easy', skillIncrease: true, description: 'Create a new camp' },
  { code: 560, abbreviation: 'AbanCmp', name: 'Abandon Camp', restrictions: ['e'], difficulty: 'easy', skillIncrease: false, description: 'Abandon a camp' },
  { code: 565, abbreviation: 'ReduPop', name: 'Reduce Population Centre', restrictions: ['e'], difficulty: 'easy', skillIncrease: false, description: 'Reduce the size of a population centre' },
  { code: 580, abbreviation: 'SprdRum', name: 'Spread Rumours', restrictions: ['e'], difficulty: 'automatic', skillIncrease: false, description: 'Spread rumours to affect loyalty' },
  { code: 585, abbreviation: 'Uncover', name: 'Uncover Secrets', restrictions: ['e'], difficulty: 'average', skillIncrease: false, description: 'Uncover hidden information' },
  { code: 734, abbreviation: 'NamEmis', name: 'Name New Emissary', restrictions: ['e', 'cap'], difficulty: 'automatic', skillIncrease: false, description: 'Create a new emissary character' },
  { code: 949, abbreviation: 'TrOwner', name: 'Transfer Ownership', restrictions: ['e'], difficulty: 'easy', skillIncrease: false, description: 'Transfer ownership of a population centre' },

  // MAGE SKILL ORDERS
  { code: 120, abbreviation: 'CstHlSp', name: 'Cast Heal Spell', restrictions: ['m'], difficulty: 'varies', skillIncrease: true, description: 'Cast a healing spell on a character' },
  { code: 330, abbreviation: 'CstCjSp', name: 'Cast Conjuring Spell', restrictions: ['m'], difficulty: 'varies', skillIncrease: true, description: 'Cast a conjuring spell' },
  { code: 700, abbreviation: 'ForgtSp', name: 'Forget Spell', restrictions: ['m'], difficulty: 'automatic', skillIncrease: false, description: 'Forget a known spell' },
  { code: 705, abbreviation: 'RsrchSp', name: 'Research Spell', restrictions: ['m'], difficulty: 'varies', skillIncrease: true, description: 'Research a new spell' },
  { code: 710, abbreviation: 'PrenMgy', name: 'Prentice Magery', restrictions: ['m'], difficulty: 'automatic', skillIncrease: true, description: 'Train an apprentice mage' },
  { code: 737, abbreviation: 'NamMage', name: 'Name New Mage', restrictions: ['m', 'cap'], difficulty: 'automatic', skillIncrease: false, description: 'Create a new mage character' },
  { code: 940, abbreviation: 'CstLoSp', name: 'Cast Lore Spell', restrictions: ['m'], difficulty: 'varies', skillIncrease: true, description: 'Cast a lore spell for information' },

  // MOVEMENT ORDERS
  { code: 810, abbreviation: 'MovChar', name: 'Move Character', restrictions: ['without'], difficulty: 'automatic', skillIncrease: false, description: 'Move a character to a new location' },
  { code: 820, abbreviation: 'MovCmpy', name: 'Move Company', restrictions: ['c', 'company'], difficulty: 'automatic', skillIncrease: false, description: 'Move a company to a new location' },
  { code: 825, abbreviation: 'CstMvSp', name: 'Cast Movement Spell', restrictions: ['m', 'without'], difficulty: 'varies', skillIncrease: true, description: 'Cast a movement spell' },
  { code: 830, abbreviation: 'MovNavy', name: 'Move Navy', restrictions: ['com'], difficulty: 'automatic', skillIncrease: false, description: 'Move a navy unit' },
  { code: 840, abbreviation: 'Stand', name: 'Stand and Defend', restrictions: ['com'], difficulty: 'automatic', skillIncrease: false, description: 'Stand and defend position' },
  { code: 850, abbreviation: 'MovArmy', name: 'Move Army', restrictions: ['com'], difficulty: 'automatic', skillIncrease: false, description: 'Move an army to a new location' },
  { code: 860, abbreviation: 'ForcMar', name: 'Force March Army', restrictions: ['com'], difficulty: 'automatic', skillIncrease: false, description: 'Force march an army (faster but morale loss)' },
  { code: 870, abbreviation: 'MovJoin', name: 'Move Character & Join Army', restrictions: ['without'], difficulty: 'automatic', skillIncrease: false, description: 'Move character and join an army' },

  // MARKET ORDERS
  { code: 310, abbreviation: 'BidCar', name: 'Bid from Caravans', restrictions: [], difficulty: 'automatic', skillIncrease: false, description: 'Bid on goods from caravans' },
  { code: 315, abbreviation: 'PrchCar', name: 'Purchase from Caravans', restrictions: [], difficulty: 'automatic', skillIncrease: false, description: 'Purchase goods at market price' },
  { code: 320, abbreviation: 'SellCar', name: 'Sell to Caravans', restrictions: [], difficulty: 'automatic', skillIncrease: false, description: 'Sell goods at market price' },
  { code: 325, abbreviation: 'NatSell', name: 'Nation Sell to Caravans', restrictions: ['cap'], difficulty: 'automatic', skillIncrease: false, description: 'Nation-wide sell order' },

  // MISCELLANEOUS ORDERS
  { code: 285, abbreviation: 'ReacEnc', name: 'Reaction to Encounter', restrictions: [], difficulty: 'automatic', skillIncrease: false, description: 'React to an encounter' },
  { code: 290, abbreviation: 'InvEnc', name: 'Investigate Encounter', restrictions: [], difficulty: 'automatic', skillIncrease: false, description: 'Investigate an encounter' },
  { code: 360, abbreviation: 'TrArt', name: 'Transfer: Artifacts', restrictions: [], difficulty: 'automatic', skillIncrease: false, description: 'Transfer artifacts between characters' },
  { code: 363, abbreviation: 'TrHost', name: 'Transfer: Hostages', restrictions: [], difficulty: 'automatic', skillIncrease: false, description: 'Transfer hostages between characters' },
  { code: 660, abbreviation: 'RansOff', name: 'Offer Ransom', restrictions: ['c', 'cap'], difficulty: 'automatic', skillIncrease: false, description: 'Offer ransom for a hostage' },
  { code: 740, abbreviation: 'RtrChar', name: 'Retire Character', restrictions: [], difficulty: 'automatic', skillIncrease: false, description: 'Retire a character' },
  { code: 755, abbreviation: 'JnCmpy', name: 'Join Company', restrictions: [], difficulty: 'automatic', skillIncrease: false, description: 'Join a company' },
  { code: 760, abbreviation: 'LvCmpy', name: 'Leave Company', restrictions: ['without'], difficulty: 'automatic', skillIncrease: false, description: 'Leave a company' },
  { code: 765, abbreviation: 'SplArmy', name: 'Split Army', restrictions: ['c', 'com'], difficulty: 'automatic', skillIncrease: false, description: 'Split an army into two' },
  { code: 785, abbreviation: 'JnArmy', name: 'Join Army', restrictions: ['without'], difficulty: 'automatic', skillIncrease: false, description: 'Join an army' },
  { code: 790, abbreviation: 'LvArmy', name: 'Leave Army', restrictions: ['without'], difficulty: 'automatic', skillIncrease: false, description: 'Leave an army' },
  { code: 792, abbreviation: 'DropArt', name: 'Drop Artifact', restrictions: [], difficulty: 'automatic', skillIncrease: false, description: 'Drop an artifact' },
  { code: 794, abbreviation: 'AnchShp', name: 'Anchor Ships', restrictions: ['c', 'com'], difficulty: 'automatic', skillIncrease: false, description: 'Anchor ships at a port' },
  { code: 796, abbreviation: 'PickArt', name: 'Pick up Artifact', restrictions: [], difficulty: 'easy', skillIncrease: false, description: 'Pick up an artifact' },
  { code: 798, abbreviation: 'PickShp', name: 'Pick up Ships', restrictions: ['c', 'com'], difficulty: 'automatic', skillIncrease: false, description: 'Pick up ships' },
  { code: 805, abbreviation: 'UsMvArt', name: 'Use Movement Artifact', restrictions: [], difficulty: 'automatic', skillIncrease: false, description: 'Use a movement artifact' },
  { code: 900, abbreviation: 'FindArt', name: 'Find Artifact', restrictions: [], difficulty: 'hard', skillIncrease: false, description: 'Search for an artifact' },
  { code: 935, abbreviation: 'UsScArt', name: 'Use Scrying Artifact', restrictions: [], difficulty: 'automatic', skillIncrease: false, description: 'Use a scrying artifact' },
  { code: 942, abbreviation: 'MvTnMap', name: 'Move Turn Map', restrictions: ['fa', 'cap'], difficulty: 'average', skillIncrease: false, description: 'Move the turn map (Fourth Age)' },
  { code: 945, abbreviation: 'UsHiArt', name: 'Use Hiding Artifact', restrictions: [], difficulty: 'automatic', skillIncrease: false, description: 'Use a hiding artifact' },
  { code: 947, abbreviation: 'NatTran', name: 'Nation Transport', restrictions: ['cap'], difficulty: 'automatic', skillIncrease: false, description: 'Transport goods nationally' },
  { code: 948, abbreviation: 'TranCar', name: 'Transport by Caravan', restrictions: ['cap'], difficulty: 'automatic', skillIncrease: false, description: 'Transport goods by caravan' },
  { code: 960, abbreviation: 'IncrCar', name: 'Increase Caravan Prices', restrictions: ['fa', 'cap'], difficulty: 'hard', skillIncrease: false, description: 'Increase caravan prices' },
  { code: 965, abbreviation: 'ReduCar', name: 'Reduce Caravan Prices', restrictions: ['fa', 'cap'], difficulty: 'hard', skillIncrease: false, description: 'Reduce caravan prices' },
  { code: 990, abbreviation: 'OneRing', name: 'The One Ring', restrictions: [], difficulty: 'automatic', skillIncrease: false, description: 'Attempt to use the One Ring' },
];
