import { SpellDefinition, SpellCategory } from '../types/spells';

export const SPELL_DEFINITIONS: SpellDefinition[] = [
  // HEALING SPELLS
  { id: 2, name: 'Minor Heal', category: 'healing', minCastingRank: 10, description: 'Heal minor wounds' },
  { id: 4, name: 'Major Heal', category: 'healing', minCastingRank: 30, description: 'Heal major wounds' },
  { id: 6, name: 'Greater Heal', category: 'healing', minCastingRank: 50, description: 'Heal severe wounds' },
  { id: 8, name: 'Heal True', category: 'healing', minCastingRank: 70, description: 'Heal all wounds completely' },

  // DEFENSIVE SPELLS
  { id: 102, name: 'Barriers', category: 'defensive', minCastingRank: 10, description: 'Create magical barriers' },
  { id: 104, name: 'Resistances', category: 'defensive', minCastingRank: 20, description: 'Grant magical resistances' },
  { id: 106, name: 'Deflections', category: 'defensive', minCastingRank: 30, description: 'Deflect incoming attacks' },
  { id: 108, name: 'Blessings', category: 'defensive', minCastingRank: 40, description: 'Bless troops for protection' },
  { id: 110, name: 'Protections', category: 'defensive', minCastingRank: 50, description: 'Grant magical protections' },
  { id: 112, name: 'Shields', category: 'defensive', minCastingRank: 60, description: 'Create magical shields' },
  { id: 114, name: 'Barrier Walls', category: 'defensive', minCastingRank: 70, description: 'Create walls of barriers' },
  { id: 116, name: 'Force Walls', category: 'defensive', minCastingRank: 80, description: 'Create walls of force' },

  // OFFENSIVE SPELLS
  { id: 202, name: 'Call Fire', category: 'offensive', minCastingRank: 10, description: 'Call forth fire' },
  { id: 204, name: 'Wild Flames', category: 'offensive', minCastingRank: 15, description: 'Unleash wild flames' },
  { id: 206, name: 'Wall of Fire', category: 'offensive', minCastingRank: 20, description: 'Create a wall of fire' },
  { id: 208, name: 'Words of Pain', category: 'offensive', minCastingRank: 25, description: 'Speak words of pain' },
  { id: 210, name: 'Words of Calm', category: 'offensive', minCastingRank: 30, description: 'Speak words of calm (defensive)' },
  { id: 212, name: 'Words of Paralysis', category: 'offensive', minCastingRank: 35, description: 'Paralyze enemies' },
  { id: 214, name: 'Call Winds', category: 'offensive', minCastingRank: 40, description: 'Call forth winds' },
  { id: 216, name: 'Wild Winds', category: 'offensive', minCastingRank: 45, description: 'Unleash wild winds' },
  { id: 218, name: 'Wall of Wind', category: 'offensive', minCastingRank: 50, description: 'Create a wall of wind' },
  { id: 220, name: 'Words of Agony', category: 'offensive', minCastingRank: 55, description: 'Cause agony' },
  { id: 222, name: 'Words of Stun', category: 'offensive', minCastingRank: 60, description: 'Stun enemies' },
  { id: 224, name: 'Words of Command', category: 'offensive', minCastingRank: 65, description: 'Issue magical commands' },
  { id: 226, name: 'Chill Bolts', category: 'offensive', minCastingRank: 70, description: 'Launch chill bolts' },
  { id: 228, name: 'Frost Balls', category: 'offensive', minCastingRank: 75, description: 'Launch frost balls' },
  { id: 230, name: 'Wind Storms', category: 'offensive', minCastingRank: 80, description: 'Create wind storms' },
  { id: 232, name: 'Fire Bolts', category: 'offensive', minCastingRank: 85, description: 'Launch fire bolts' },
  { id: 234, name: 'Fire Balls', category: 'offensive', minCastingRank: 90, description: 'Launch fire balls' },
  { id: 236, name: 'Fire Storms', category: 'offensive', minCastingRank: 95, description: 'Create fire storms' },
  { id: 238, name: 'Summon Wind Spirits', category: 'offensive', minCastingRank: 60, description: 'Summon wind spirits' },
  { id: 240, name: 'Summon Fire Spirits', category: 'offensive', minCastingRank: 70, description: 'Summon fire spirits' },
  { id: 242, name: 'Words of Death', category: 'offensive', minCastingRank: 80, description: 'Speak words of death' },
  { id: 244, name: 'Fearful Hearts', category: 'offensive', minCastingRank: 85, description: 'Cause fear in hearts' },
  { id: 246, name: 'Summon Storms', category: 'offensive', minCastingRank: 90, description: 'Summon storms' },
  { id: 248, name: 'Fanaticism', category: 'offensive', minCastingRank: 95, description: 'Inspire fanaticism' },

  // MOVEMENT SPELLS
  { id: 302, name: 'Long Stride', category: 'movement', minCastingRank: 10, description: 'Increase movement range' },
  { id: 304, name: 'Fast Stride', category: 'movement', minCastingRank: 20, description: 'Greatly increase movement' },
  { id: 306, name: 'Path Mastery', category: 'movement', minCastingRank: 30, description: 'Master all paths' },
  { id: 308, name: 'Capital Return', category: 'movement', minCastingRank: 40, description: 'Return to capital' },
  { id: 310, name: 'Major Return', category: 'movement', minCastingRank: 50, description: 'Return to major town' },
  { id: 312, name: 'Return True', category: 'movement', minCastingRank: 60, description: 'Return to any friendly PC' },
  { id: 314, name: 'Teleport', category: 'movement', minCastingRank: 80, description: 'Teleport to any location' },

  // LORE SPELLS
  { id: 402, name: 'Perceive Allegiance', category: 'lore', minCastingRank: 10, description: 'Perceive nation allegiance' },
  { id: 404, name: 'Perceive Relations', category: 'lore', minCastingRank: 15, description: 'Perceive nation relations' },
  { id: 406, name: 'Divine Army', category: 'lore', minCastingRank: 20, description: 'Divine information about armies' },
  { id: 408, name: 'Perceive Nationality', category: 'lore', minCastingRank: 25, description: 'Perceive character nationality' },
  { id: 410, name: 'Divine Allegiance Forces', category: 'lore', minCastingRank: 30, description: 'Divine allegiance forces' },
  { id: 412, name: 'Research Artifact', category: 'lore', minCastingRank: 35, description: 'Research an artifact' },
  { id: 413, name: 'Scry Population Centre', category: 'lore', minCastingRank: 40, description: 'Scry a population centre' },
  { id: 414, name: 'Scry Hex', category: 'lore', minCastingRank: 45, description: 'Scry a hex' },
  { id: 415, name: 'Scry Area', category: 'lore', minCastingRank: 50, description: 'Scry an area' },
  { id: 416, name: 'Reveal Production', category: 'lore', minCastingRank: 55, description: 'Reveal PC production' },
  { id: 417, name: 'Divine Characters With Forces', category: 'lore', minCastingRank: 60, description: 'Divine characters with forces' },
  { id: 418, name: 'Locate Artifact', category: 'lore', minCastingRank: 65, description: 'Locate an artifact' },
  { id: 419, name: 'Divine Nation Forces', category: 'lore', minCastingRank: 70, description: 'Divine nation forces' },
  { id: 420, name: 'Reveal Character', category: 'lore', minCastingRank: 75, description: 'Reveal a hidden character' },
  { id: 422, name: 'Perceive Power', category: 'lore', minCastingRank: 80, description: 'Perceive magical power' },
  { id: 424, name: 'Perceive Mission', category: 'lore', minCastingRank: 85, description: 'Perceive character mission' },
  { id: 426, name: 'Divine Army True', category: 'lore', minCastingRank: 90, description: 'Divine army information perfectly' },
  { id: 428, name: 'Locate Artifact True', category: 'lore', minCastingRank: 95, description: 'Locate artifact perfectly' },
  { id: 430, name: 'Reveal Character True', category: 'lore', minCastingRank: 100, description: 'Reveal character perfectly' },
  { id: 432, name: 'Perceive Secrets', category: 'lore', minCastingRank: 60, description: 'Perceive hidden secrets' },
  { id: 434, name: 'Reveal Population Centre', category: 'lore', minCastingRank: 70, description: 'Reveal hidden PC' },
  { id: 436, name: 'Scry Character', category: 'lore', minCastingRank: 50, description: 'Scry a character' },

  // CONJURING SPELLS
  { id: 502, name: 'Weakness', category: 'conjuring', minCastingRank: 40, description: 'Conjure weakness (lost spell)' },
  { id: 504, name: 'Sickness', category: 'conjuring', minCastingRank: 50, description: 'Conjure sickness (lost spell)' },
  { id: 506, name: 'Curses', category: 'conjuring', minCastingRank: 60, description: 'Conjure curses (lost spell)' },
  { id: 508, name: 'Conjure Mounts', category: 'conjuring', minCastingRank: 70, description: 'Conjure mounts (lost spell)' },
  { id: 510, name: 'Conjure Food', category: 'conjuring', minCastingRank: 80, description: 'Conjure food (lost spell)' },
  { id: 512, name: 'Conjure Hordes', category: 'conjuring', minCastingRank: 90, description: 'Conjure hordes (lost spell, DS only)' },
];
