export interface OrderSchemaField {
  label?: string;
  placeholder?: string;
  help?: string;
}

export interface OrderSchema {
  help?: string;
  fields?: Record<string, OrderSchemaField>;
}

const H = (help: string): OrderSchema => ({ help });

export const ORDER_SCHEMAS: Record<number, OrderSchema> = {
  100: {},
  175: H('Changes your nation side. Pick carefully.'),
  180: H('Improves relations with another nation.'),
  185: H('Worsens relations with another nation.'),
  205: H('Equips a held weapon-type artifact (+command).'),
  210: H('Duel to the death unless refused. Winner gains skill and morale shifts.'),
  215: H('Refuses every challenge this turn; a commander may lose morale.'),
  225: H('Needs a known combat spell. Applies in its force battle. +1 mage skill.'),
  230: H('Attacks everything in the hex. Winner: +1 command, +2 training.'),
  235: H('Attacks one nation forces in the hex. Winner: +1 command, +2 training.'),
  240: H('+5 morale, +1 training. Holds position, no attack.'),
  250: H('Assaults the PC in the hex to destroy it.'),
  255: H('Assaults the PC in the hex to capture it.'),
  260: H('Marks siege: loyalty -20. No assault yet.'),
  270: H('Destroys warships of your first navy. +1 command.'),
  275: H('Scuttles transports of your first navy.'),
  280: H('Abandons all ships of your first navy.'),
  300: { help: 'Clamped 10-80. Loyalty drifts with the tax rate.', fields: { newRate: { placeholder: '40' } } },
  340: H('Moves food from nation reserve to the army.'),
  345: H('Moves food from the army to the nation reserve.'),
  347: H('Moves food between your armies.'),
  349: H('Moves war machines between your armies.'),
  351: H('Moves weapon ranks between your armies.'),
  353: H('Moves armour ranks between your armies.'),
  355: H('Moves troops (all 6 types) between your armies.'),
  357: H('Not implemented yet: message only.'),
  370: H('One material only; sets assigned types to its rank. Shows gold + material cost live.'),
  375: H('One material only; sets assigned types to its rank. Shows gold + material cost live.'),
  400: H('Cavalry costs mounts. Capped by PC capacity, gold and mounts.'),
  404: H('Cavalry costs mounts. Capped by PC capacity, gold and mounts.'),
  408: H('Capped by PC capacity and gold.'),
  412: H('Capped by PC capacity and gold.'),
  416: H('Capped by PC capacity and gold.'),
  420: H('Capped by PC capacity and gold.'),
  425: H('Retires troops for 10 gold each.'),
  430: H('+5 morale, +1 command.'),
  435: H('+10 morale, +1 command.'),
  440: H('50 gold + 10 timber + 5 steel each. Needs own PC at the army.'),
  444: H('Raises armour ranks toward 100. 5 gold + 5 leather + 2 steel per point.'),
  448: H('Raises weapon ranks toward 100. 5 gold + 3 bronze + 1 steel per point.'),
  452: H('1000 gold + timber each. Needs own coastal PC with port/harbour.'),
  456: H('1000 gold + timber each. Needs own coastal PC with port/harbour.'),
  460: H('Removes the harbour.'),
  465: H('Removes the port.'),
  470: H('Destroys stores at the PC.'),
  475: H('Needs command or own PC in the hex; roll decides.'),
  480: H('Removes fortifications.'),
  490: H('Needs river; major rivers need road. Timber + gold shown live.'),
  494: H('One level per turn. Timber comes from PC stores.'),
  498: H('Lowers loyalty without attacking.'),
  725: H('Creates a new character (takes a name).'),
  728: H('Creates a new commander (takes a name).'),
  745: H('Creates a company for 500 gold.'),
  750: H('Disbands the character company.'),
  770: H('Hires a fresh army at the capital.'),
  775: H('Disbands the army.'),
  780: H('Transfers army command. -5 morale.'),
  925: H('Recon the area (simplified roll for now).'),
  950: H('Moves the capital. 25000 gold.'),
  600: H('Counter-espionage (simplified roll for now).'),
  605: H('Guards a location against enemy agents.'),
  610: H('Guards a character against assassination.'),
  615: H('Kill the target. Same-side targets allowed at your risk.'),
  620: H('Target must be alive and free.'),
  625: H('Target must be a hostage.'),
  630: H('Target must be a hostage.'),
  635: H('Target must be a hostage.'),
  640: H('Target must be a hostage.'),
  645: H('Target must be a hostage.'),
  650: H('Target must be a hostage.'),
  655: H('Target must be a hostage.'),
  665: H('Needs bridge at the hex.'),
  670: H('Downgrades fortifications at the PC.'),
  675: H('Removes harbour/port at the PC.'),
  680: H('Destroys stores and -50 production at the PC.'),
  685: H('Steals the artifact for your nation.'),
  690: H('Steals gold from the victim nation.'),
  731: H('Creates a new agent (takes a name).'),
  905: H('Scouts armies at the hex.'),
  910: H('Scouts the area (simplified roll for now).'),
  915: H('Scouts one hex (simplified roll for now).'),
  920: H('Scouts the population centre.'),
  930: H('Scouts characters at the hex.'),
  500: H('Plants a spy in ONE nation. Only one active asset per nation.'),
  505: H('Recruits only from non-played same-side nations (<21 chars); otherwise a bribed agent with intel. Min 500 gold, more improves odds.'),
  520: H('Raises loyalty of your own PC.'),
  525: H('Lowers foreign loyalty and makes relations neutral both ways.'),
  530: H('Harbour to port: 1500 gold + 2500 timber.'),
  535: H('New harbour: 2500 gold + 5000 timber.'),
  550: H('Improves the PC one step.'),
  552: H('Settles a camp for 4000 gold. Empty name picks from your nation pool.'),
  555: H('Creates a camp for 2000 gold. Empty name picks from your nation pool.'),
  560: H('Abandons your camp here.'),
  565: H('Shrinks the PC one step, -20 loyalty.'),
  580: H('Plants false rumours (design pending, see rumores_580_585.txt).'),
  585: H('Discovers secrets and rumours (design pending, see rumores_580_585.txt).'),
  734: H('Creates a new emissary (takes a name).'),
  949: H('Transfers PC ownership to your nation.'),
  120: H('Needs a valid known healing spell. Optional target must share the hex. +1 mage skill on success.'),
  330: H('Needs a valid known conjuring spell. +1 mage skill on success.'),
  700: H('Forgets a known spell.'),
  705: H('Learns a new spell (random if empty). Starts at rank 0.'),
  710: H('Trains the mage: +2 on success.'),
  737: H('Creates a new mage (takes a name).'),
  940: H('Target depends on the spell: character, nation, artifact, population centre, army or hex. +1 mage skill on success.'),
  810: H('Moves within 14 MP budget. Evasive costs double.'),
  820: H('Moves the company.'),
  825: H('Needs a valid known movement spell. Teleports the force.'),
  830: H('Moves the navy (1 MP open water). Storm risk.'),
  840: H('Holds position.'),
  850: H('Moves the army within budget.'),
  860: H('Longer march, morale loss. Hardy nations lose less.'),
  870: H('Moves and joins the army at destination.'),
  310: H('Bids at caravan prices. Market prices are fixed for now.'),
  315: H('Buys at caravan prices. Market prices are fixed for now.'),
  320: H('Sells stock for gold. 20000 gold sell cap per turn.'),
  325: H('Sells a percentage of stock. 20000 gold sell cap per turn.'),
  285: H('Reacts to a known encounter here.'),
  290: H('Investigates rumours and encounters in the hex.'),
  360: H('Moves an artifact between characters.'),
  363: H('Moves a hostage. Target must be kidnapped.'),
  660: H('Offers ransom.'),
  740: H('Retires the character.'),
  755: H('Joins a company of your nation.'),
  760: H('Leaves the company.'),
  765: H('Splits the army in half.'),
  785: H('Joins the army (moves there too).'),
  790: H('Leaves the army.'),
  792: H('Drops the artifact at the hex.'),
  794: H('Anchors ships at the location.'),
  796: H('Picks up an artifact.'),
  798: H('Picks up ships at the location.'),
  805: H('Uses a held movement artifact.'),
  900: H('Searches for an artifact.'),
  935: H('Uses a held scrying artifact.'),
  942: H('Fourth Age only.'),
  945: H('Uses a held hiding artifact.'),
  947: H('Not implemented: creates resources (stub).'),
  948: H('Not implemented: creates resources (stub).'),
  960: H('Fourth Age only, no handler yet.'),
  965: H('Fourth Age only, no handler yet.'),
  990: H('Stub: lone d6, no Ring logic yet.'),
};
